### ISSUE TITLE
Event handles are not released on Windows server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3335]
**Imported issue:**
- Author: Daniel Mnch
- Date: 2012-10-18 18:37:46
- Legacy ID: 3405

On my system synergys.exe has been running continuously since April 20012.

Having a look at the Windows Handle count, I nearly got a shock:

**more than 15.120.000 active Handles !!!**

A tiny fraction (about 90) seems fairly normal:
- 34 EtwRegistration Handles
- 11 Key Handles
- 11 Thread Handles **(for 7 objects; one of them refers to a "non-existing Process" (!) )**
- 8 TpWorkerFactory Handles **(for 2 objects)**
- 4 ALPC Port Handles
- 3 Timer Handles
- 2 Directory Handles
- 2 IoCompletion Handles
- 2 Process Handles **(1 is a non-existing Process(!))**
- 2 Section Handles
- 2 Semaphore Handles
- 2 WindowStation Handles **(for 1 object)**
- 1 Desktop Handle
- 1 File Handles
- 1 KeyEvent Handle
- 1 Mutant Handle
- 1 Token Handle

The rest of the **15 mio.** Handles consist of Event Handles:

43 of them are unnamed and each only references a same object 1-2 times.

All other 15 mio. Event Handles reference the same object:
- Handle Name: \BaseNamedObjects\SendSAS
- Type: Event
- Description: A synchronization object
- References:
  - References:.15.120.687
  - Handles:.......15.120.685
- Signaled: FALSE

**Steps to reproduce:**
1. Start synergys.exe (Server, might be problematic as client too) and let it run for a while
2. Monitor it via Process Explorer (originates at sysinternals . com)

if not already:

 2.1 menu -> view -> Show Lower Pane

 2.2 menu -> view -> Lower Pane View -> Handles

 2.3 click the bottom column with alternate mouse key and select all entries to show

**Versions and operating systems:**

Cannot find information about the Synergy version anywhere.
But it was the latest available 64 bit version back on 6th of February 2012.

OS:
Win 7 Enterprise SP1 x64

**Temporary workarounds:**

None

**Additional comments:**

None

**Comment by the-wes** [comment]
Pretty sure this is still happening in 1.6.2. Still getting reports of it, anyway.

**Comment by andreialecu** [comment]
Possibly related: https://github.com/synergy/synergy/issues/4577#issuecomment-97054735

**Comment by badger200** [comment]
I just witnessed a bug in 1.7.1 that resulted in 17,000+ Handles in less than 1 week uptime on my WinXP SP3 Pro system. I've been using Synergy for years and I monitor my system constantly (hourly) with Process Hacker (an open source Process Explorer clone) and I notice big handle leaks very quickly. 

Therefore, this Handle leak must be new because I just upgraded to 1.7.1 recently and do not recall this issue with 1.6.3 or any prior versions. 

The Handle leak all seemed to be in pairs for (1) non-existent Processes and (2) Winlogon.exe. Very strange, I don't recall seeing that behavior before in any app. I have many power user / developer tools on my system if there's anything I can do to help? (But I am not a programmer.)

**Comment by nbolton** [comment]
@badger200 Which process has the 17k+ handles?

**Comment by badger200** [comment]
@nbolton Unfortunately I don't recall and didn't capture a screenshot. I haven't seen the problem reoccur - however, ever since a certain upgrade maybe 3-6 months ago, Synergy has been acting weird where if I boot up, my NT service automatically starts and connects my XP machine (server) to my Mac (client), but I don't have any system tray icon or user interface whatsoever. 

If I start Synergy from the Start Menu, it seems to act as though it's completely unaware of the NT service already running, and it tries to start its own server and fails endlessly repeating, and I have to do some juggling of restarting the service and closing the Synergy program before it works again.

Since I wrote that the 1.7.1 Handle leak occurred shortly after I upgraded to 1.7.1, I almost suspect it's possible I upgraded and then started Synergy, resulting in the above weird conflicting situation, rather than rebooting. So that's possibly the scenario where it leaks handles.

I guess a bigger question is - why does Synergy 1.7x no longer seem to have an ability to configure the NT service? I seem to recall this could be configured and you could pick the system account to use and whether it should be started automatically etc.?

**Comment by charles-peter-nystrom** [comment]
I am still running into this issue on 1.11.1-stable-55ec3105 on Windows 10.0.18362, killed the synergyd process with 280k handles after running about 10 hours.

**Comment by MindMusic** [comment]
Same here... Synergy has 1,500,000 handles!  What the heck?!?

**Comment by andreacndn** [comment]
This has been fixed in more recent versions, I am afraid.
