### ISSUE TITLE
Mouse won't go to second (X11) screen

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3460]
**Imported issue:**
- Author: Brian Murrell (Brian J. Murrell)
- Date: 2013-03-06 21:38:37
- Legacy ID: 3530

**Steps to reproduce:**
1. Install synergy on dual-head system (details below)
2. Add a synergy client
3. Try to move mouse to second screen

Expected: The mouse should move to the second screen

Actual: The mouse jumps to the middle of the synergy client's screen

Synergy server: Ubuntu 12.04 with Synergy 1.3.8

On the machine I run my synergy server on (i.e. where the mouse and keyboard are physically connected) I have two screens (i.e. :0.0 and :0.1).  :0.1 is to the left of :0.0.  I configure the synergy server to allow a client to connect on the right.  At this point (no client connected yet) I can move my mouse from the :0.0 to the left onto the :0.1 screen with no problem.

As soon as I connect the client on right I can move my mouse off of the right of my :0.0 screen onto the synergy client machine and back with no problem.  However when I try to move the mouse off of :0.0 onto :0.1 on the left, as soon as the mouse leaves :0.0 it jumps to the middle of the synergy client screen on the right.  I can then of course move the mouse back from the synergy client onto the :0.0 screen but again, if I continue moving the mouse to the left to try to put it onto the :0.1 screen, it jumps back onto the synergy client screen.

The only way to resolve this is to revert the synergy server back to 1.3.6.

**Comment by brianjmurrell** [comment]
And still happening on F21 with synergy-1.4.10-6.fc21.

Any chance, at all of getting this fixed?  Given that the versions between where this was working and stopped working are pretty near, it ought to be not-too-difficult for somebody familiar with the code/changes/design to pinpoint this problem.  Any chance of getting that to happen?

**Comment by nbolton** [comment]
Thanks for the info @brianjmurrell!

**Comment by brianjmurrell** [comment]
FWIW, I've re-built 1.3.6 on F20 and F21 and now moving the mouse horizontally to the client works again.  I guess I am just going to continue to use 1.3.6 until this is fixed.

I suppose I should alert the Fedora maintainer about this and the fact that >1.3.6 on Linux doesn't seem to offer anything (in my use-case at least) so perhaps they want to stick with that until this bug is fixed.

**Comment by legonigel** [comment]
I did a little looking at this. I had some trouble figuring out the commit history because of all the refactoring that has been done since 1.4.  I believe the fix should be in [`synergy/src/lib/platform/XWindowsScreen.cpp`](https://github.com/synergy/synergy/blob/master/src/lib/platform/XWindowsScreen.cpp). It took some time but I made a diff between 1.3.7 and 1.4.10 
```
git diff 143c4cd2975988cc122654eb7dde11d07c1c6a96..2136d733c946cb675089852255f107c9f112ff1c -- src/lib/platform/CXWindowsScreen.cpp
```

I could be completely wrong though, but I think this is a start.

**Comment by brianjmurrell** [comment]
@legonigel is there a patch you would like me to try applying to see if it fixes this?

**Comment by legonigel** [comment]
@brianjmurrell Not yet. Just started looking at it. I will post back if i have a patch.

**Comment by brianjmurrell** [comment]
@legonigel I wonder if you have made any progress with this issue yet?
