### ISSUE TITLE
Customize ctrl-alt-del emulation on Windows servers

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#3821]
**Imported issue:**
- Author: The Wes
- Date: 2014-01-21 01:47:31
- Legacy ID: 3891

The pause/break key is starting to be phased out of keyboards. At the least, we should switch the ctrl-alt-del emulation hotkey to ctrl-alt-end to match with the standard set by MSTSC. Ideally, this should be configurable by the user in the main GUI.

If hotkeys were configurable per-client, I think it would belong under Configure Server -> Hotkeys. There should be an entry by default upon installation that looks like:

keystroke(Ctrl+Alt+End) -> keystroke(Ctrl+Alt+Del,*)

or similar.

However, since that would currently cause the keystroke to be sent to all clients, implementing the above would require fixing that first. So as a stop-gap, we should perhaps put it under Advanced Server Settings.

**Comment by kayhadrin** [comment]
Could I ask why this was marked as obsolete?

Has this been implemented already?

**Comment by nbolton** [comment]
@the-wes

**Comment by the-wes** [comment]
kayhadrin - it was marked obsolete because it hadn't been updated in a long time. we can re-open any that are still outstanding. please let me know if you come across any others.

**Comment by kayhadrin** [comment]
Alright, so if the issue is not officially fixed yet, here's a detailed workaround that I'm using after gathering different bits of info over the internet. 

Context: 
- Synergy server: Windows 7 machine aka `desktop`
- client: another Windows 7 machine aka `laptop`

I made sure to enable the ["software secure attention sequence policy" on Win7](https://support.realvnc.com/Knowledgebase/Article/View/339/6/how-can-i-enable-the-software-secure-attention-sequence-policy) (sorry, I forgot where I found this link somewhere else on StackOverflow).

I defined the following shortcuts:

- Trigger Ctrl+Alt+Del: `keystroke(Shift+Alt+l) = ;switchToScreen(laptop); keystroke(Control+Alt+Delete,laptop)`
- Refocus on server screen: `keystroke(Shift+Alt+h) = ;switchToScreen(desktop)`

I use them with this sequence:

1. Trigger the Ctrl+Alt+Del shortcut from my desktop machine. This focuses on the laptop's login screen.
2. Enter my username and password on the laptop. 
After successful login, my mouse cursor is sent back to the desktop screen for some reason
3. Move the mouse to the laptop screen again 
4. Trigger the "refocus" shortcut to go back to the desktop screen.
This is important because otherwise, there's a bug in Synergy that causes the main desktop to "think" that the `Ctrl` key is continuously pressed down. So it becomes hard to type text or click on buttons without adverse side-effects.
5. Now, both screens are usable as usual.

I hope it'll be useful to someone else.
