### ISSUE TITLE
Invisible cursor on Ubuntu 14.04

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4070]
**Imported issue:**
- Author: Tol PHOBOS
- Date: 2014-08-27 18:46:19
- Legacy ID: 4140

**Steps to reproduce:**
1. Install Synergy premium client 1.5.x on Ubuntu 12.04.5, with Synergy premium server 1.5.x on Win7 (tested with 1.5.0 and 1.5.1)
2. Migrate to Ubuntu 14.04.1
3. Restart computer
4. Try to go from server to client : the cursor is invisible. You are able to select or click, but the cursor is not visible on client screen.
5. The only workaround is to connect a mouse on client and to use it : the cursor is visible now, and you can use it from server.
6. The workaround must be applied after each client reboot.

Expected: back to visible cursor without workaround

Actual: cursor invisible. Tested with Synergy 1.5.0 & 1.5.1 ... no difference.

**Versions and operating systems:**

Synergy : 1.5.1 Premium
Server : Windows 7 64bits SP1 FR Familly Premium (retail)
Client : Ubuntu 14.04.1 64bits Desktop

**Temporary workarounds:**

Connect a mouse on client and to use it : the cursor is visible now.

**Comment by jcalfee** [comment]
Ubuntu 14.04 to Ubuntu 14.04 .. The first transition from server to client gives an invisible but functional mouse pointer.  Touching the client's mouse pad will make the cursor show up.  Or, moving back to the server then to the client again will make the mouse pointer show up.

**Comment by TedRinehart** [comment]
Had this issue, only the cursor didn't return. After running a command I found [here](http://itsfoss.com/invisible-mouse-cursor-ubuntu-1310/), the cursor returned.

The command, in case anyone else has this issue.
`gsettings set org.gnome.settings-daemon.plugins.cursor active false`

**Comment by mwlebour** [comment]
+1

**Comment by davehaddon** [comment]
This problem has started for me since installing 15.04. As I was rebraining the machine, I also finally made the change to SSL with Synergy, so I can't say for sure which has caused the problem.

With the previous version, on 14.04, I did not get a cursor on the login screen, but it returned once the desktop was shown

The gsettings command has fixed the problem (after rebooting).



 

Client: Ubuntu with Synergy 1.7.3.  
Server: OSX 10.10.3 with Synergy 1.7.3

**Comment by shhrohan** [comment]
@TedRinehart your command did fix the issue for me. thanks a lot.

**Comment by dlebauer** [comment]
@TedRinehart +1 for `gsettings set org.gnome.settings-daemon.plugins.cursor active false`.

**Comment by Peaches491** [comment]
@TedRinehart Another +1 for `gsettings set org.gnome.settings-daemon.plugins.cursor active false`
It would be really nice to not need this after every restart =p

**Comment by ajj** [comment]
@TedRinehart gsettings fixes it here too. Server on OS X 10.11 even warns "cursor may not be visible". Hope we get a fix ...

**Comment by TedRinehart** [comment]
Glad the fix I located is able to help you guys.

**Comment by W3BGUY** [comment]
I'm seeing this same issue on Ubuntu 17.10.  Works fine on Kali-Rolling, but not Ubuntu.

**Comment by Syridian** [comment]
I too am seeing this same issue on 17.10.  Synergy connects, and I'm able to see that the mouse pointer is there only due to mouse-over effects.  I can draw a selection box on the desktop if I guess where the mouse is.  Keyboard also works if I can manage to click into the right spot on the screen to input text.

Server is Windows 10, 1.8.8 Stable, client is Ubuntu 17.10, 1.8.8 Stable.

I have tried the gsettings solution above but it doesn't make any difference.  The Log seems to be reporting everything is connected and working fine.  I'm not sure it's entirely a problem with Synergy.  I have tried the beta 2.0 and not had much success with getting that connecting.  Reinstalled on both server and client, no difference.  

I've tried googling for solutions as I feel this is something simple, but I'm not finding much that is helpful.  Can anyone please point me in the right direction?

**Comment by GavinF17** [comment]
Issues with 17.10 seem to be with the switch from X.Org to Wayland for the default display server, when you are logging in click on the cog icon beside the Sign In button and select "Ubuntu on Xorg" and then log in as normal

@W3BGUY @Syridian

**Comment by Syridian** [comment]
@GavinF17,
That was my initial thought too, but I have tried using X.Org and it doesn't seem to make a difference.  I do need to fully confirm that as it was one of the first tests I did in my attempts to diagnose the issue and when it didn't work I moved on to other things.

**Comment by CastleSeven** [comment]
Same issue for me on 17.10

**Comment by choldgraf** [comment]
I have the same issue running synergy on W10 trying to control Ubuntu 17.10

**Comment by carlosbrb** [comment]
It works if you use ubuntu xorg which can be selected if you click the "cog" icon on the login screen. New ubuntu uses the "wayland" display manager, which may not be supported.

Solution found here: https://symless.com/forums/topic/4393-no-mouse-and-keyboard-input-on-ubuntu-1710-client/

**Comment by mrscherrycoke** [comment]
@carlosbrb  +1 for that. 
Btw, here is how to change to xorg.  
https://itsfoss.com/switch-xorg-wayland/
