### ISSUE TITLE
Ubuntu client's mouse is invisible every other time

### ISSUE THREAD

**Issue by hoboX10** [symless/synergy-core#4289]
Every other time I move the mouse from my Windows servers to the Ubuntu client, the mouse changes between being invisible (still is moving and can interact with stuff) and being normally visible. I can sit there moving it back and forth repeatedly watching it go from invisible to visible for seemingly no reason.

**Comment by the-wes** [comment]
I have heard this from other users as well. I have no explanation.

**Comment by dennisgrieten** [comment]
Also have the same problem. Pointer flashes for an instant on client screen.

**Comment by estyrke** [comment]
I have an observation that may be interesting: I'm using a Swedish keyboard. I have a "language switcher" at both server (windows) and client (Ubuntu 15.04) to switch between Swedish and English layout. Both systems are currently set to "sv" and when I mouse over to the Linux client, the cursor disappears and when I type I get a Swedish layout as expected. *However*, when I then mouse back to the server and again to the client (the mouse cursor is now visible), the language switcher *on the server* now shows "en", and when I type I get an English layout. I.e. the keyboard switches to English if and only if the cursor is visible, and stays at Swedish if and only if the cursor is invisible.

It seems transient though, because now I did something to make this phenomenon go away, and I can't seem to reproduce it again. Maybe it's totally unrelated...

**Comment by BudgieInWA** [comment]
I also experience this, including the pointer flashing for an instant on client screen.

Interestingly, I have a touch screen on my client. When I touch the screen (as a feature) the pointer is hidden (and using a mouse local to the client the pointer is again made visible). If I then move the pointer back to the server (using synergy, which does not reshow the pointer) then back to the client, it will be visible. That is the pointer always adopts the opposite state to when it left.

**Comment by estyrke** [comment]
I have a touchscreen on the client too, and noticed the same behavior. If I disable it using "xinput disable <id>", the problem goes away. It seems it then works even if I re-enable it again.

**Comment by meawoppl** [comment]
This seems very similar to the issue above, suggesting it may not be OS specific, can everyone involved describe which computer is hosting, and which computer the cursor vanishes for?

**Comment by BudgieInWA** [comment]
Server: Windows 7, 64 bit  
Client: Ubuntu 14.04, 64 bit

My touch device on the client is listed as 'Atmel Atmel maXTouch Digitizer' if that helps.

**Comment by BudgieInWA** [comment]
I too can stop this from happening by disabling then re-enabling the touchscreen using `xinput`. That is, this only happens when synergy starts while the touchscreen is enabled (and until it is disabled).

**Comment by estyrke** [comment]
@meawoppl The symptomps in this bug (happens every other time, touchscreen related, Ubuntu client) seem to have nothing in common with #2754 (happens always, cursor reappears after certain actions, Mac client) other than the fact that the cursor disappears in some circumstances. I think this bug report should be kept exclusively for the problem described in the OP, i.e. "cursor disappears/reappears every other time it's moved from client to server and back". That being said, it seems like many people having *this* bug have commented in the *other* thread (#2754), making that thread somewhat confusing.

My setup:
Server: Windows 7, 64 bit
Client: Ubuntu 15.04, 64 bit, with 'Atmel Atmel maXTouch Digitizer' touchscreen device.

By the way, today it doesn't seem to work to disable and then re-enable the digitizer, I have to keep it disabled to prevent the cursor from disappearing.

**Comment by deanrather** [comment]
I've also got this issue.

A Left: Windows 8.1 Server
B Middle: Ubuntu 15.04 Client
C Right: Ubuntu 15.04 Client
When moving the mouse from B to C, every 2nd time, the cursor is invisible. Every other time, it's visible.

Logs on B and C indicate "INFO: entering screen" and "INFO: leaving screen", but no warnings about cursor visibility.

Logs on A indicate "INFO: switch from b to c at x,y" and "INFO: switch from c to b at x,y", but no warnings or errors.

All devices are running Synergy Pro 1.7.3 with SSL turned off.

_Note:_ Device B has a touch-screen!

**Comment by meawoppl** [comment]
Hmmmmm, I have a touch screen too . . . possibly related to multiple pointing devices?

**Comment by estyrke** [comment]
And probably specifically to Ubuntu's practice of hiding the pointer when using a touchscreen. I've traced this behavior to the cursor plugin of ubuntu-settings-daemon. Running `gsettings set org.gnome.settings-daemon.plugins.cursor active false` to disable it (and then restarting the session) makes this problem go away for me. However, the side effect is that the mouse cursor remains visible also when using the touchscreen.

**Comment by deanrather** [comment]
@estyrke Huzzah! That's worked for me!

**Comment by afoster** [comment]
Thanks @estyrke , this workaround also worked for me.

**Comment by roytanck** [comment]
Thank you @estyrke ! This worked for me too. I don't use the touch screen much, so it's a completely acceptable workaround for me. Nice catch.

**Comment by razem-io** [comment]
Workaround sadly doesn't seem to work with Xubuntu which uses XFCE instead of Gnome. The Server (Windows 10 Laptop) has a touchscreen which seems to be the source of the issue.

**Comment by sbzen** [comment]
Guys,

A clever guy posted the solution. Just put both monitors under the same text size adjust and it the mouse appears. It happens to me that my monitors have different resolution so in one of them I adjusted the "size of text".

Have a good day!

![image](https://cloud.githubusercontent.com/assets/14254421/9834314/011f8ac8-5983-11e5-9c4b-5ca380b459b0.png)


SBZen

**Comment by kukkuk** [comment]
I have the same problem. Server: Ubuntu 14.04, Client (was also 14.04) upgraded to 15.10.

My client is a ThinkPad with touch screen. So I created a small script in /usr/local/bin/fixpointer.sh :
```bash
#!/bin/bash
xinput disable 9
xinput enable 9
```

(9 is the ThinkPad's touch screen).

It fixes the problem immediately. My cursor was also invisible every second entry to the client.

**Comment by melscoop** [comment]
@estyrke - excellent, your suggestion for gsettings worked for me instantly, no need to restart the session

Running Gnome shell on CentOS 7.1.1503

**Comment by anisse-astier** [comment]
The gsettings suggestion from @estyrke  didn't work, but @kukkuk 's trick of disable the touchscreen with xinput worked somehow on my touchscreen laptop. Now to guess why it happens…

**Comment by kukkuk** [comment]
What's also interesting, is that once I ran that script, it kept working,
even after rebooting the laptop.

**Comment by acron0** [comment]
@kukkuk Be aware, device numbers can change, so I use

```
xinput list | grep "ELAN" | sed -E "s/.*id=([0-9]+).*/\\1/" | xargs xinput --disable
```

(My touchscreen is listed as 'ELAN Touchscreen')

**Comment by kukkuk** [comment]
Thanks @acron0 . Does the device number change, even on the same laptop? Or is it just different for different laptops?

**Comment by acron0** [comment]
@kukkuk Well, I had it change on the same laptop. I had a script very similar to you, for turning off my touchpad when I was working (I was never able to get the 'disable touchpad when typing' gimmicks to work so I just toggle it with a key combo). At some point my script failed because the touchpad device number changed - possibly due to USB devices being plugged in.

**Comment by kukkuk** [comment]
Thanks @acron0 . Good to know.

**Comment by apocalysque** [comment]
I'm having this same problem too.  Windows server and ubuntu client.  I have a mouse attached to the screen and it will show the cursor if I move the attached mouse, but not if I don't.  On a centos box the cursor would show every other time I moved to that screen.

**Comment by alexandercerutti** [comment]
Here, on Ubuntu 15.10 installed on a Surface Pro 3 (that is a touchscreen), I suffer of this problem but I found how to bypass it. I suspect that it is caused by a conflict between multiple mouse input sources, mouse and touch, even if it isn't in using but active.

I solved by disabling and re-enabling the touch source first looking for the id with **xinput**, and then executing
`xinput disable 15; xinput enable 15`

These are my peripherals:

![schermata del 2016-07-12 00-42-55](https://cloud.githubusercontent.com/assets/5442545/16749340/c76658bc-47c9-11e6-95d7-925cd016754d.png)
If the TypeCover Mouse is my classic pointer and id#15 is the touchscreen.

This works even if done before Synergy start. So, I suggest to create a script to execute at the startup. I'm trying to create an Upstart script, but I'm failing (I'm not understanding very well how to create it).

**Comment by sarathpetec** [comment]
I'm also facing the same issue.

**Comment by nmvictor** [comment]
What worked for me was to log out and start session "Ubuntu on Xorg". This option can be accessed by pressing the settings icon on the LDM/GDM Ubuntu 17.10.

**Comment by luchillo17** [comment]
@nmvictor Did you logged out of both? i have 2 ubuntu 17.10 and having issues with Synergy 2 connecting.

**Comment by nmvictor** [comment]
Synergy 2 did not work for me, demanded a refund (which was issued) and reverted to synergy 1. So can’t help with synergy 2 Issues. Sorry.

**Comment by luchillo17** [comment]
I might end up the same, i've contacted support, let's see how it goes.

**Comment by emmanuelcohen** [comment]
Using Surface Pro on Windows 10 and Synergy 1.6.3 (server)
+ Ubuntu 16.04 and Synergy 1.6.2 (client)
My cursor was hidden once every other time.

`$ gsettings set org.gnome.settings-daemon.plugins.cursor active false 
`
did it for me.

**Comment by r1fl** [comment]
workaround doesnt work for me. any updates?

**Comment by Snuggle** [comment]
I have the same issue. gsettings workaround doesn't work for me.
Fedora w/ GNOME Wayland <-> KDE Plasma

**Comment by WWWobbly** [comment]
Hi folks. Just wanted to say I love Synergy and also to say that the workaround from estyrke is still relevant. I am not a programmer but cut and copying his command has held up well over a 24 hour period where the original problem described would require a Linux Mint 20.1 restart about every 5 to 20 minutes as a client with a Win10 box as the server.

I have a specific set of circumstances whereby I am using a Win10 Lenovo laptop as the server with another Lenovo laptop as a client (both with touchscreens) and an old 2009 27" iMac running Linux Mint 20.1. Strangely, it is the Mint iMac with no touchscreen or trackpad that would lose cursor visibility, although it was apparent that the mouse and keyboard were actually still functioning via Synergy. Restarting the Cinnamon environment or Xorg or logging off and then on again would not resolve the problem. Only a complete reboot of the Linux Mint machine would restore the cursor but not for long and I could not determine what task or movement was triggering the fault.

After searching carefully, I came across this thread and just copied and blindly pasted estyrke's original command to the Linux Mint box and I am nice and stable now. I have not tested if this command sticks after a reboot.

Ross.

**Comment by fatihky** [comment]
Hi, I had the same problem and I've finally figured it out. The latest ubuntu uses Wayland instead of the XOrg display server. After logging out and selecting "Ubuntu with XOrg" solved my problem.

**Comment by tspearconquest** [comment]
Please reopen. This is not solved.

**Comment by andreacndn** [comment]
https://github.com/symless/synergy-core/issues/4289#issuecomment-125449759 has a working solution
https://github.com/symless/synergy-core/issues/4289#issuecomment-821988826 has also a positive comment about Wayland vs Xorg

**Comment by tspearconquest** [comment]
That's not a *solution*, it is a *workaround*

A solution will be required to make this work on Wayland for users who either have no choice to install Xorg due distribution maintainers not offering it, or who have no desire to switch back to Xorg.

**Comment by andreacndn** [comment]
@tspearconquest Wayland support is outside the scope of this bug report.

**Comment by tspearconquest** [comment]
We can also say that requiring the user to change settings for a touch screen in such a way that the mouse remains visible while using the touchscreen is not a valid solution to the issue. The issue is that the mouse cursor disappears. Anything less than identifying the problem as either a bug in Wayland or a bug in synergy is not going to cut it here. I've paid for this product and donated to Nick several times and I expect this to be fixed.

**Comment by tspearconquest** [comment]
> @tspearconquest Wayland support is outside the scope of this bug report.

To be clear I'm not asking for Wayland support, I'm asking for a proper triage of the issue to be performed and then for someone to check if this is actually a bug in synergy, or if it's an issue that synergy is encountering because of a bug in Wayland. I will report the issue to Wayland if it's found to be their issue to solve but I want to make sure this issue is triaged properly.

**Comment by Speeddymon** [comment]
Please reopen this per my previous request.

**Comment by Speeddymon** [comment]
Please reopen this. I am also still seeing this issue on Wayland. If Synergy supports Xorg, why won't you support Wayland?
