### ISSUE TITLE
SSL plugin 'ns' is not compatible with old Mac OS X versions

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#4648]
10.6 user reported...

```
ERROR: failed to load plugin: libns.dylib
FATAL: An error occurred: dlopen(/Users/dlw/Library/Synergy/Plugins/libns.dylib, 1): Library not loaded: /usr/lib/libcurl.4.dylib
Referenced from: /Users/dlw/Library/Synergy/Plugins/libns.dylib
Reason: Incompatible library version: libns.dylib requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
```

Also reported on 10.7: `exit code 1, looking for libns.dylib`

**Comment by Caroljroberts** [comment]
OK, so I signed up for another post account regarding this issue. Hopefully I will get notification when this will be resolved?

**Comment by nbolton** [comment]
Just bumped this up to 1.7.3. I will try my hardest to get this to you guys within 2 weeks.

**Comment by Caroljroberts** [comment]
Hope so.  Missing this feature between my PC & MAC something fierce.

**Comment by jerrt010** [comment]
just started the update round on my three computers that use Syngergy.  having this exact problem with my 10.6 mac book pro.  Glad someone else is having this problem.  Thanks for updates!

**Comment by Caroljroberts** [comment]
I've tried downloading the 1.6.0 MAC OS X 10.6, and the same for my PC.  The PC is working and running Synergy; however, my MAC is not cooperating as I can't even open the installation instructions.

**Comment by nbolton** [comment]
Will be solved by #4695

**Comment by nbolton** [comment]
@speaker When solving #4695 (modifying 'dist-ftp' toolchain command), we should upload the built dylib's for each version of Mac OS X. However, we also need the GUI to download the specific version of the dylib for the OS X version running.

**Comment by nbolton** [comment]
Will be solved by #4696

**Comment by nbolton** [comment]
Sorry guys, this one has missed the 1.7.3 release, we'll try to solve it in the next release.

**Comment by Caroljroberts** [comment]
Downloaded newest version to both PC and MAC.  Got the PC connected to server (MAC), but had to disarm the SSL settings.  The MAC is still totally unresponsive with the following message:NOTE: starting server
NOTE: config file: /var/folders/bw/bwEfr8VBHB4maWiCKybc+++++TI/-Tmp-/qt_temp.J32123
NOTE: log level: INFO
INFO: drag and drop enabled
NOTE: crypto disabled because of ns plugin not available
NOTE: started server, waiting for clients
ERROR: failed to load plugin 'libns.dylib', error: dlopen(/Users/carolroberts/Library/Synergy/Plugins/libns.dylib, 1): Library not loaded: /usr/lib/libcurl.4.dylib
  Referenced from: /Users/carolroberts/Library/Synergy/Plugins/libns.dylib
  Reason: Incompatible library version: libns.dylib requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /var/folders/bw/bwEfr8VBHB4maWiCKybc+++++TI/-Tmp-/qt_temp.u32123
NOTE: log level: INFO
INFO: drag and drop enabled
ERROR: failed to load plugin 'libns.dylib', error: dlopen(/Users/carolroberts/Library/Synergy/Plugins/libns.dylib, 1): Library not loaded: /usr/lib/libcurl.4.dylib
  Referenced from: /Users/carolroberts/Library/Synergy/Plugins/libns.dylib
  Reason: Incompatible library version: libns.dylib requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
NOTE: crypto disabled because of ns plugin not available
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: new client is unresponsive
NOTE: accepted client connection
NOTE: accepted client connection
NOTE: client "Carol-HP" has connected
NOTE: new client is unresponsive
NOTE: new client is unresponsive
NOTE: new client is unresponsive
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /var/folders/bw/bwEfr8VBHB4maWiCKybc+++++TI/-Tmp-/qt_temp.E32123
NOTE: log level: INFO
INFO: drag and drop enabled
ERROR: failed to load plugin 'libns.dylib', error: dlopen(/Users/carolroberts/Library/Synergy/Plugins/libns.dylib, 1): Library not loaded: /usr/lib/libcurl.4.dylib
  Referenced from: /Users/carolroberts/Library/Synergy/Plugins/libns.dylib
  Reason: Incompatible library version: libns.dylib requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
NOTE: crypto disabled because of ns plugin not available
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: client "Carol-HP" has connected
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /var/folders/bw/bwEfr8VBHB4maWiCKybc+++++TI/-Tmp-/qt_temp.K32123
NOTE: log level: INFO
INFO: drag and drop enabled
ERROR: failed to load plugin 'libns.dylib', error: dlopen(/Users/carolroberts/Library/Synergy/Plugins/libns.dylib, 1): Library not loaded: /usr/lib/libcurl.4.dylib
  Referenced from: /Users/carolroberts/Library/Synergy/Plugins/libns.dylib
  Reason: Incompatible library version: libns.dylib requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: client "Carol-HP" has connected
NOTE: stopping synergy desktop process
NOTE: starting server
NOTE: config file: /var/folders/bw/bwEfr8VBHB4maWiCKybc+++++TI/-Tmp-/qt_temp.O32123
NOTE: log level: INFO
INFO: drag and drop enabled
ERROR: failed to load plugin 'libns.dylib', error: dlopen(/Users/carolroberts/Library/Synergy/Plugins/libns.dylib, 1): Library not loaded: /usr/lib/libcurl.4.dylib
  Referenced from: /Users/carolroberts/Library/Synergy/Plugins/libns.dylib
  Reason: Incompatible library version: libns.dylib requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
NOTE: started server, waiting for clients
NOTE: accepted client connection
NOTE: client "Carol-HP" has connected

**Comment by the-wes** [comment]
Anyone running 10.6 or 10.7, you will have to delete the plugin file in order to start Synergy.

**Comment by Caroljroberts** [comment]
I think this was done.  What¹s happening now is that it loses communication
with my 2nd computer.....it crashes and I have to restart it.

Carol Roberts

**Comment by dvincent** [comment]
I think I might have a related issue on this client computer, with OS X Lion 10.7.5.  This seems to be the key part of the client log:

    [2015-08-24T21:02:12] INFO: drag and drop enabled
    [2015-08-24T21:02:12] NOTE: crypto disabled because of ns plugin not available
    [2015-08-24T21:02:12] NOTE: started client
    [2015-08-24T21:02:12] NOTE: connecting to 'mariel.local': 192.168.1.2:24800
    [2015-08-24T21:02:12] ERROR: failed to load plugin 'libns.dylib', error: dlopen(/Users/dvincent/Library/Synergy/Plugins/libns.dylib, 1): Symbol not found: _NXArgv
      Referenced from: /Users/dvincent/Library/Synergy/Plugins/libns.dylib
      Expected in: /usr/lib/libSystem.B.dylib
     in /Users/dvincent/Library/Synergy/Plugins/libns.dylib

Encryption was OK with 1.6.3, though I suspect that's no help to the reader.

**Comment by Caroljroberts** [comment]
Interesting.  I have Snow Leopard 10.6.8.  I haven¹t made the update, as I¹m
afraid to.  I had a lot of issues, then had to wait for the fix as someone
was on vacation.

**Comment by dvincent** [comment]
I think I might have the same issue on this computer, with OS X Lion 10.7.5.  This seems to be the key part of the client log:

    [2015-08-24T21:02:12] INFO: drag and drop enabled
    [2015-08-24T21:02:12] NOTE: crypto disabled because of ns plugin not available
    [2015-08-24T21:02:12] NOTE: started client
    [2015-08-24T21:02:12] NOTE: connecting to 'mariel.local': 192.168.1.2:24800
    [2015-08-24T21:02:12] ERROR: failed to load plugin 'libns.dylib', error: dlopen(/Users/dvincent/Library/Synergy/Plugins/libns.dylib, 1): Symbol not found: _NXArgv
      Referenced from: /Users/dvincent/Library/Synergy/Plugins/libns.dylib
      Expected in: /usr/lib/libSystem.B.dylib
     in /Users/dvincent/Library/Synergy/Plugins/libns.dylib

Encryption was OK with 1.6.3, though I suspect that's no help to the reader.

**Comment by docdawning** [comment]
I'm using OS X 10.7.5, and I have the exact same issue
`ERROR: failed to load plugin 'libns.dylib', error: dlopen....`

Judging by the fact I'm running Synergy 1.7.6 and the discussion here's getting dated, this probably isn't going to be getting fixed? :\

**Comment by jwwalker** [comment]
Same issue here with OS X 10.7.5 on the server.  Tried 1.8.2 and 1.7.6.
