### ISSUE TITLE
Can't move mouse to other screen if some application hangs

### ISSUE THREAD

**Issue by Katulus** [symless/synergy-core#4687]
When I run some application on Windows that temporarily hangs (is doing some work and UI of that application is unresponsive for a while) I can't move the mouse to the other screen until it gets responsive again.

One example:
1) Open some solution in Microsoft Visual Studio 2012/2013/2015
2) It takes some time to load the solution and VS seems to be frozen during that. 
3) I get busy mouse cursor on VS window but I can work with any other application on the same computer without issues.
4) When I try to move the mouse to the other computer screen I can't. Mouse is locked on first machine.
5) Once VS does the work and becomes responsive again (busy mouse cursor is gone) I can move the mouse to the other screen without issues.

**Comment by speaker** [comment]
Synergy requires information and processing power from the machine that is the current active target in order to run. If the server, for example, becomes so busy that windows isn't sending events to synergy, there is no way for synergy to pass those along.

In development this causes no end to frustration so we usually add --no-hooks to the command line. (In VS, right click "synergys" and open "Properties" Open up "Debugging" under "Configuration Properties" and add --no-hooks near the begonning. this will prevent the mouse form ever leaving the server. (It does still connect to all clients so that aspect can be tested.))

**Comment by Katulus** [comment]
This issue is not about server becoming busy. Machine where mouse pointer is is perfectly fine, CPU is for example 20%. Only one application (in my example Visual Studio, but can be anything else) is not responding, rest of the system responds properly.
I don't see why single frozen application should prevent Synergy from working properly.
