### ISSUE TITLE
Cursor flickers in center of Linux client on entering

### ISSUE THREAD

**Issue by dsemi** [symless/synergy-core#4741]
This issue is intermittent, but there are times when moving the mouse from server to client, the mouse gets "stuck" and jumps between the middle of the client screen and the edge where it entered the client screen. I'm very confident this is not a network issue as my two computers are directly connected to a switch, so the traffic should be almost direct.
Running Windows 8.1 64 bit for the server and Arch Linux 64 bit on the client.

[Here](https://www.youtube.com/watch?v=nRfV2NMPEeA&feature=youtu.be#t=16s)'s a video of what happens (Server on the right, client on the left). Keep an eye on the left side of the video.  Apologies for the poor quality, but I can't screencap two computers at once ;)

EDIT: Forgot the version, Synergy 1.7.3

**Comment by vid** [comment]
I'm seeing something may be related, but it may be Ubuntu's fault. When I switch from one window to another, the cursor "sticks" at the edge. It makes Synergy aggravating to use because it's not at all seamless, I have to pause then 'wiggle' the mouse and then it jumps to an essentially random location. I've turned off sticky edges and anything that seems related in Ubuntu's settings. Thank you for any help.
