### ISSUE TITLE
Windows 8 &10 Running Synergy 1.7 Loses Registration

### ISSUE THREAD

**Issue by jenelcohen** [symless/synergy-core#5377]
Synergy Version: 1.7
Server: Windows 8, 10
Client: Windows 8. 10

Problem:

Windows 10 loses registration on reboot, resulting in the top bar to be rewritten as "UNREGISTERED".

Solution:

1) The issue will temporarily resolve when the File wizard is successfully re-run, but will reappear after reboot.

2) The issue can be resolved for some users. Completely uninstall Synergy. Make sure to search for Synergy and remove all parent folders. Reinstall as an administrator and run for the first time as an administrator.

**Comment by pmario** [comment]
>2) The issue can be resolved for some users. Completely uninstall Synergy. Make sure to search for Synergy and remove all parent folders. Reinstall as an administrator and run for the first time as an administrator.

thx for the info. I have the same problem from time to time. 

For me it only looses the registration, if I open the program on the server. 
After a reboot, the client connects just fine. Since I use encryption, it means the server has to be ok too. 
Connection is (randomly) lost, only if I open the program on the server.
ATM I don't know a way, to reliably reproduce the problem with my settings.
