### ISSUE TITLE
Failing to automatically download and install Bonjour

### ISSUE THREAD

**Issue by xhou-wavefin** [symless/synergy-core#5467]
Windows 7
1. Fresh install
2. Open GUI
3. Click yes when a messgebox prompt up asking for installing Bonjour

Expect: Automatically install Bonjour
Acutal: Nothing happens, next time restart still prompt the same messagebox.

**Comment by tscs37** [comment]
Windows 10

Same issue. Trying to install Bonjour a second time without restarting the GUI causes it to freeze.

**Comment by StoneMoe** [comment]
Same issue here.

**Comment by nlyan** [comment]
This should now be fixed. In future versions we may be eliminating this download and install step. If it still isn't working, shout and I'll reopen.

**Comment by Elektro121** [comment]
Still happening
I see the installer launching trying to install then closing (i think it's because it's already installed), but Synergy keeps asking me if i want to install the Bonjour Service. I also tried to install directly via Apple (https://support.apple.com/kb/DL999?locale=fr_FR) and he's still asking for it :/

How the app is guessing about the installation ? I want to check if it's my computer faulty in this case.
1.8.2-stable-36cd521 - Windiows 10 Pro Anniversary Update - 1607 - 14393.105

**Comment by nlyan** [comment]
@Elektro121 try uninstalling Bonjour and then manually installing the version at http://symless.com/bonjour/Bonjour.msi for Windows 32bit or http://symless.com/bonjour/Bonjour64.msi for Windows 64bit. 

Note you may have to restart the Synergy GUI, or even your machine, after this.,

**Comment by mmiat** [comment]
me too with synergy 1.8.8

**Comment by v-karbovnichy** [comment]
I also have this experience on Windows 10 Enterprise with fresh synergy 1.8.8
