### ISSUE TITLE
Key presses aren't passed to AWS Workspaces

### ISSUE THREAD

**Issue by atomic-penguin** [symless/synergy-core#5639]
### Operating Systems

Client: MacOS Sierra 10.12

Server: Fedora 22, kernel 4.4.14-200.fc22.x86_64
### Synergy Version

1.8.3-stable-db9181b
### Steps to reproduce bug

Keyboard strokes do not get passed through to [AWS Workspaces](https://aws.amazon.com/workspaces/).  Workspaces is a hosted Citrix-like Remote Desktop environment.  There are Workspaces clients for MacOS, and Windows, but not Linux.
1. Click things: mouse input passes through AWS Workspaces OSX client.  Copy/paste buffer passes through AWS Workspaces OSX client.
2. Type things: nothing happens in context of AWS Workspaces OSX client.  Keyboard input is passed through correctly to other OSX applications on the Synergy client.
### Other info
- When did the problem start to occur? When I used AWS Workspaces client with Synergy client machine.
- Is there a way to work around it? No
- Does this bug prevent you from using Synergy entirely? No

**Comment by nlyan** [comment]
Does this only effect workspaces on macOS clients? And do you have any idea if these bugs were present on macOS 10.11 (El Capitan)?

**Comment by atomic-penguin** [comment]
Do not know, never used Workspaces with 10.11.

**Comment by t0mj** [comment]
Experiencing the same issue. Mouse movements and clicks work fine but no keyboard input to the workspace.

**Comment by geekmuse** [comment]
Wanted to update this thread since the issue still exists, though in a different form.  Keyboard and mouse get passed to the Workspace, but no meta keys work (e.g. shift, ctrl, cmd/option, though interestingly caps lock key works).  

Versions of everything are as follows:

Synergy - Server (Running on RPi 3b+/armhf raspbian):  1.11.0-stable-b2173efb
Synergy - Client (Running on MacOS 10.15.7, Mid-2015 Retina 15" model): 1.11.1-stable-55ec3105
Workspaces client version:  3.0.11.1344
Workspaces OS:  Amazon Linux, kernel vsn 4.14.198-152.320.amzn2.x86_64

**Comment by phillipleroy** [comment]
> Wanted to update this thread since the issue still exists, though in a different form. Keyboard and mouse get passed to the Workspace, but no meta keys work (e.g. shift, ctrl, cmd/option, though interestingly caps lock key works).
> 
> Versions of everything are as follows:
> 
> Synergy - Server (Running on RPi 3b+/armhf raspbian): 1.11.0-stable-b2173efb
> Synergy - Client (Running on MacOS 10.15.7, Mid-2015 Retina 15" model): 1.11.1-stable-55ec3105
> Workspaces client version: 3.0.11.1344
> Workspaces OS: Amazon Linux, kernel vsn 4.14.198-152.320.amzn2.x86_64

I'm having this exact same issue.
This issue is opened since 2016 and it's unreal it's not yet fixed.

**Comment by pjrm** [comment]
I confirm this is still happening in the latest version:
Synergy - Server ( Windows 10 - Synergy 1.14.0-stable)
Synergy - Client ( MacOS X Big Sur - Synergy 1.14.0-stable)

Is it something that is in the roadmap to fix?

**Comment by pjrm** [comment]
After digging more about this issue (because without this, this software does not fit my use case), I found out in another GitHub issue here that a project called Barrier (fork of synergy) solves these issues out-of-the-box. Furthermore, it's free (you don't need to pay for SSL)  and works much better.

If anyone wants a solution, until this be fixed (probably synergy 3 will have this fixed), you can try this one: https://github.com/debauchee/barrier/.

I hope it helps people that have this ongoing issue.

**Comment by snakai** [comment]
Reported this issue to Synergy/Symless.  Even though this issue has been reported five years ago, sounds like they aren't even looking into it

"I am not finding any documentation concerning Synergy support inside of Amazon Workspaces. I can log an issue in our internal tracking system, but I am afraid I would not be able to provide much assistance beyond that."
