### ISSUE TITLE
Wayland server support

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy-core#5803]

**Comment by asdofijanw** [comment]
Any updates on being able to run a server on wayland? Ubuntu is about to switch to using Wayland, which means Mint will be not far behind. I'm afraid you're going to get another flood of unhappy comments from Ubuntu and Mint users who are suddenly not able to use synergy anymore, similar to the flood of Fedora users who posted in regards to issue #4090.

I'm a huge fan of synergy and have been using it for years and years, and I would REALLY like to be able to use it again, unfortunately that can't happen until Wayland is supported. Thanks in advance!

References:
[Ubuntu wiki - Article on Wayland](https://wiki.ubuntu.com/Wayland)
[OMG! Ubuntu! - Ubuntu Is Switching to Wayland](http://www.omgubuntu.co.uk/2017/04/ubuntu-will-run-wayland-default)

**Comment by her001** [comment]
The Ubuntu switch to Wayland as a default wouldn't happen until at least
18.04, when Gnome becomes the default desktop environment. There is no rush.

Even when it does switch, people can still use X, so it isn't all that
critical.

**Comment by randombk** [comment]
@her001 Fedora and Arch have already switched to Wayland by default.  Synergy is the last remaining application on my Arch setup that prevents me from switching.

You mentioned in a prior tweet that you had a prototype of Wayland on the client - is that available anywhere?

**Comment by Splix76** [comment]
I disagree that there is no rush as well @her001. Those of us on RHEL/Fedora/Arch and other distributions are ahead of where Ubuntu is with Gnome / Wayland and the user base justifies a fix soon.

Please fix this as I don't plan on returning to Xorg/X11 and I cannot use Synergy until the invisible mouse cursor is resolved.

**Comment by jsight** [comment]
@Splix76 - Well, there definitely has been no rush so far. I do hope that they don't plan to wait until 2018/04 to get a version supporting it out there, though. :)

**Comment by hluisi** [comment]
Well this is a bad sign.  Sad to see because I really liked synergy.  I watched the others like synergy go down this route.  Open-Source / free to owned and not free, to not adding the new features because there were other options, to why support linux at all when most only use windows and OSX.

When you have to start asking the average Joe to use X11 on Ubuntu in order get your program to work, how do you think they'll respond?

**Comment by dajones70** [comment]
I like Synergy and have supported this project multiple times financially over the years.  I run Fedora 25 and have lockups with Synergy running so I guess I will have to uninstall it until this is fixed.

**Comment by hubertlepicki** [comment]
@XinyuHou @her001 what's the progress / info on this one? 

I did some research on my own and I do think it's highly discouraged by Wayland developers to try to do what we need to be done, which may be the problem. Qt, for example, dropped it's support for setPointer(x, y) api calls because there is not corresponding underlying mechanism to do so cleanly under Wayland.

I think you would have to hook up somewhere deeper, like into libinput or (dear gods) kernel driver to emit the events, that'd be captured by wayland.

Is my research correct? Can you give us some hints on problems you are facing and if/when we will see some progress? You know, we can go to wayland devs and shout at them that we need support for simulating keyboard/mouse events and capture those if you have problem on that area ;)

**Comment by socmag** [comment]
Just purchased Synergy Pro... Installed... Doesn't work :/

Check the FAQ - oh... Wayland, and I'm running Fedora 26

Try disable Wayland - can't even log in to the desktop.

Yeah, I think supporting Wayland would probably be a very good idea.

Also real shame it doesn't work because it looks exactly what I wanted

**Comment by mtballday** [comment]
Ah...that's why it isn't working (Wayland). In addition to the comments above comments, I expect most people will install Synergy and it just won't work. They won't know why...

**Comment by krizzo** [comment]
It will be nice when this happens. I "can" run x11 but being the only application that requires x11 is a bit sad. I've been using synergy for over 10 years and donated a couple of times before it was a paid pre-compiled product. Hopefully, we won't have to wait a long time for this feature/bug.

**Comment by kdb424** [comment]
This is the only major piece of software that holds me back from wayland, which is a shame, but alas, I'll have to stick to X11. It's a complicated problem to solve, so I understand it will take time. Really hope this does eventually get sorted somehow though.

**Comment by atiensivu** [comment]
I'm a plus one here. I'm running the daily builds of Ubuntu 17.10 and Wayland is the default. I've dropped back to X for now but I suspect this will be a popular search result pretty soon. :)

**Comment by jayjaybillings** [comment]
+1

**Comment by nbolton** [comment]
Duplicates: https://github.com/symless/synergy-core/issues/4090

**Comment by CRTX** [comment]
Unhappy customer here too. I just bought this and can't use it with Ubuntu 17.10. If it's a technical issue we understand rather which is much better than saying "there's no rush".

**Comment by JaneSmith** [comment]
Is this _ever_ going to arrive? It's literally been years. I'd love to use Synergy, but it's not an option at all if it doesn't work with Wayland. I'm not going to switch to X just for this one piece of software.

**Comment by nbolton** [comment]
It was a high priority until Ubuntu decided to revert to X as the default in 18.04. So now it's a low priority, but we do plan to add support, but it requires a huge rewrite of a lot of the Linux code. I appreciate that Fedora is championing it, but it's not the most popular distro. Since Ubuntu 18.04, we've heard almost nothing about Wayland, so it'd be unwise for us to prioritize it.

**Comment by nbolton** [comment]
I really to appreciate how frustrated our RPM-based users are about the lack of Wayland support; however, we must prioritize what is affecting most of our users. It would be foolish to focus on the issue that affects the smallest number of users.

**Patches welcome.**

**Comment by afranke** [comment]
> Patches welcome.

GNOME did reach out to you and offer to help, and while you (@nbolton) initially took on the offer, your developer never followed up. We can’t really help if you don’t play ball.

**Comment by nbolton** [comment]
> our developer never followed up

Ah, sorry to hear that. Could you reach out to me via email and let me know the best person at GNOME to pick this back up with? nick@symless.com

**Comment by jayjaybillings** [comment]
You're right Nick. However, for those of us who paid for a license and only found out after the fact that 1) Wayland was not supported and 2) that it won't be supported, this stings.


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by debek** [comment]
Hi,
Today I installed Synergy on my Arch and now I am reading about problem with Wayland.
It is so annoying... :/

**Comment by nbolton** [comment]
> paid for a license

Please let us know if you'd like a refund. https://symless.com/synergy/refund-policy

>  that it won't be supported

Actually, we do plan to add support for Wayland. As I said earlier: "So now it's a low priority, but we do plan to add support."

Please refer to this issue for further info: https://github.com/symless/synergy-core/issues/4090
