### ISSUE TITLE
International keyboards

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy-core#6005]
All the issues related to international keyboards

**Comment by bupemko** [comment]
'ő' 'ű' pressed on Win10 server with Hungarian layout is rendered in Win7 client as 'o' and 'u'.

**Comment by grigorovich** [comment]
Server: 1.8.8, MacOS 10.12.4
Client: 1.8.8, MacOS 10.12.4

Switch lang works well but just few keys transfer incorrect symbols (lang keyslayout depended). Its not the serious bug, i just back focus on client and switch lang and keys works fine, fix like dat right now. 

I can fill full description of problem.

**Comment by paul-suarez** [comment]
Server:Ubuntu 16.04.02 (xenial), and Synergy 1.8.7-stable-9799e96
Client:Windows 7, and Synergy 1.8.4-stale-a6ff907
Both runs with a spanish keyboard.

When I try to use commands as combinations of AltGr+Something, it does not work.
If I keep pressing AltGr and start pressing the numerical keys that are on top of the keyboard, this is what I get: \|@#¬{[]}\
But when trying those commands on the second computer, this is what I get: #

If those keys are not implemented, maybe they should be added to newer versions of synergy

[Forum Thread](https://symless.com/forums/topic/2502-keys-combinations-not-recognized/)

**Comment by btaens** [comment]
With a windows server, and both a Linux and Macintosh client, all 3 configured with hungarian keyboard layout, ő and ű transfer incorrectly.
On a Linux client ő turns into õ, while ű turns into û.
On a Mac client, ő doesn't transfer at all, while ű turns into ^u.

**Comment by andyn** [comment]
The root cause of these issues is not layout specific, see #6157. Fixing it would require sending the raw keycodes over the network. I don't know if this is possible with cross-platform layouts, but I don't think there should be too many problems at least with symmetric Linux-Linux setups.

The old US layout is a special case without duplicate mappings, so it just happens to work by chance.

**Comment by LeadManPL** [comment]
Server: synergy-v1.8.8-stable-25a8cb2-Linux-x86_64.deb
Client: synergy-v1.8.8-stable-25a8cb2-Windows-x64.msi

patben@patbenamd:~/.synergy/SSL$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

patben@patbenamd:~/.synergy/SSL$ uname -a
Linux patbenamd 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

patben@patbenamd:~/.synergy/SSL$ env | grep LC_ | sort
LC_ADDRESS=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_MONETARY=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_NUMERIC=pl_PL.UTF-8
LC_PAPER=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8

PROBLEM:
On standard physical layout US keyboard, with polish language setup, Right_Alt+'sign' should be -> some polish diacritic sign. Instead nothing appears on the screen. mapping below:

Right_Alt+a -> 'ą'
Right_Alt+c -> 'ć'
Right_Alt+e -> 'ę'
Right_Alt+l -> 'ł'
Right_Alt+n -> 'ń'
Right_Alt+o -> 'ó'
Right_Alt+s -> 'ś'
Right_Alt+x -> 'ź'
Right_Alt+z -> 'ż'

I can provide additional info or debug if needed

**Comment by bupemko** [comment]
I have the same issue even in 2.0 Beta 4...

**Comment by LeadManPL** [comment]
@bupemko : meaning, which issue? Because this "Issue" is related to "All the issues related to international keyboards" as written at the beginning by @XinyuHou .

**Comment by bupemko** [comment]
Same as mentioned by previous post, same I had in 1.8... Some accented characters are not working properly.

**Comment by Cheesebaron** [comment]
My keyboard and mouse is attached to a Mac which is the server.

On my client which is a Windows 10 machine, pressing Right Alt, AutoHotkey shows it as Left Alt. Could you please distinguish between Right and Left alt?

**Comment by dannysuls** [comment]
I'm having exactly this issue, for *years*:
https://github.com/symless/synergy-core/issues/6147
Summary: writing diacritics using a US international keyboard does not work on the (Windows) client.

I'm getting *very* frustrated that this is still not fixed. I used Synergy versions 1.6.x, 1.7.x and stopped using it out of frustration somewhere around 1.8.x.

Today, I gave Synergy another try, and alas with version 2.01 this issue is still present.

**Comment by dannysuls** [comment]
FYI, I got some information from Symless that a fix for my issue is expected in version 2.1, which should come out early 2018.

**Comment by tavasti** [comment]
I can't get any characters which need AltGR on windows client. @|{[]}  missing, and for coder / linux admin this means no work can be done.

**Comment by ilganna** [comment]
Hello,

just want to report my issue as well. Here's as much details I can provide

Server is on Linux (Fedora 27), version is latest 1.9.1
Client is on Windows (Windows 10 64bit), version is latest 1.9.1

I have a Swiss French keyboard layout and my initial issue, on the Windows client, was writing special chars like "@ \ | etc" in which you need to press the alt gr key followed by the correct key. 
Note that on bot OS's I have the Swiss French keyboard layout and on the Linux host, I am able to type all special characters without any issues. (for example in terminal or text editor)

For a general overview, please check the Swiss French keyboard layout here:
https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/KB_Swiss.svg/900px-KB_Swiss.svg.png

I have solved partially my issue by using "alt gr= shift" line on config file.

Now if I keep "alt gr + 2" the Windows client produce the @ symbol. However, I am not able to type other special characters by using the "Shift" modifier; if I press "shift + 2" I expect to to have the " symbol, or if I press "shift + ¨" should produce the ! character. On the Windows client nothing is generated, while if I do on the Linux client, everything works like a charm.

I have played a bit and found out that if, in the Windows client, I change the keyboard layout to US International one, (no other layouts than US Int.) I am able to type most of the keys, also the one with the "alt + gr" modifier. But still no luck with " and ! (using shift modifier).

If I add also the Swiss French layout (on the Windows client), along with the US International, then all keys are working fine, but as I noticed on the system tray, the keyboard layouts are swapped on the fly by Windows while typing special key combinations. This would take Word, Outlook, Excel (2016), to hang/freeze due to the continuous flip of the keyboard layouts.

I would like to have only one keyboard layout in the Windows client, but losing some important keys like " ! or \ is kind of show stopper, then having two layouts may reach almost my goal, but instability of productivity softwares, is another no-go.

As per now, I cannot test on the 2.x client due to the fact that config file (alt gr = shift) line is not supported and overwritten back from the cloud.

Thanks!

**Comment by Marax** [comment]
Server: 1.10.0, Win 10
Client: 1.10.0, Win 7

Using czech querty keyboard on both machines:

"ě š č ř ž ý á í é ů ú" => "**e** š **c r** ž ý á í é **u** ú"

Problematic characters: ě č ř ů

**Comment by eltricos** [comment]
Why is this marked as fixed?

**Comment by nbolton** [comment]
Hi all, the issue is actually not fixed, but was instead closed because it's too broad. Please raise a new issue if you have a specific problem, including as much detail as possible.
