### ISSUE TITLE
Lock screen issues

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy-core#6006]
All issues related to lock screen

**Comment by bupemko** [comment]
When the server is locked I have to be very careful not to accidentally move the mouse over to the Windows 7 client otherwise I won't be able to tpye my user/pass to unlock the Windows 10 server. Can be rather frustrating sometimes.

**Comment by prikril** [comment]
@bupemko
I have a workaround for this until it is fixed:
Just disconnect the server or the client from your network or stop the synergy process on your client.
After a few seconds the mouse pointer will jump back to the screen of your server.

**Comment by b33rcity** [comment]
I have a (partially) automated workaround for this. YMMV. My particular situation is that if I mouse to a client screen the mouse pointer gets trapped in the bottom right corner. As @prikril says, restarting the client process will resolve the issue (until next time). Since both of my clients are linux boxes, I wrote a bash script that I can call from the terminal since the keyboard still works. You will need to have a keyboard shortcut for bringing up a terminal window just in case you didn't have one running when the issue started. Anyway, here's the code:

`#!/usr/bin/env bash

###############################################################################
# Resets synergy in the event that a client machine abducts the mouse.
###############################################################################

lhost=$(hostname)
processes=$(ps -eo pid,command | grep synergy | cut -f 2 -d " " | tr "\n" " ")
kill $processes
sleep 4
synergyc -f --no-tray --debug INFO --name $lhost 192.168.1.10:24800`

Potential issue with this script: in case grep decides to misbehave and not insert a leading space as it does on my machine, you may need to change the field number fed to cut. You can insert echo $processes above the kill line to make sure that the pipeline is doing what I bloody well told it to. 

Sorry, windows guys. This won't help you if you don't have cygwin or some other way to run bash scripts on your machine. I'd be interested to see an equivalent PS script, though!

**Comment by Canule** [comment]
From build 15063.250 dll patching is no longer necessary to disable that annoying lock screen, since creators update you should be able to disable by this reg value.
```
;Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization]
"NoLockScreen"=dword:00000001
```

**Comment by alanhoyle** [comment]
Ubuntu 17.10 server (default Gnome desktop), macOS 10.13.2 client, both on Synergy 1.8.8.  if I leave the cursor on the client, the server never goes to sleep, but when I bring the mouse back to the server, it goes to sleep after a fraction of a second, but there's enough time to type/paste in a command.  This has been a problem for a looong time.    https://github.com/symless/synergy-core/issues/4229
