### ISSUE TITLE
Configure individual screen separately

### ISSUE THREAD

**Issue by molecular** [symless/synergy-core#6095]
I have a feature request and I've seen a lot of people with a similar need.

The situation is when one has multiple x display on client, server or both.

You'd really want to be able to specify the links (up/down/left/right) per display and not just per host. Both the target and source of the links could be named as <host>:<x display id> (':' is probably problematic, '.' also, so maybe something else can be used here)

Example (host1 has 2 displays, host2 only one)

```
section: screens
  host1:
  host2:
end

section links:
  host2:
    left: host1:0
    up: host1:1
  host1:0
    right: host2
  host1:1
    down: host2
end
```

**Comment by dtwaling** [comment]
Yes, a monitor aware config would be a perfect enhancement!

This is something I have thought about for a long time since I have 5-6 monitors going at once for my work.  Synergy has made it nice to have at least one monitor dedicated to a secondary PC so I don't have to RDP, and I have a separate monitor dedicated to my server RDP sessions.  The only issue is, that there are always 4 monitors on the main PC but one is offset, making the shared "edge" via synergy is a little clunky.
So, YES PLEASE, develop monitor aware edge config.  maybe use the monitor number assigned by the system (i.e.: the number that displays when you click "Identify monitors"), and within square bracket specify monitor#/side?  (...just use l,r,t,b to spec side instead of full word)
PC1:
     [3l](0,100) = LT2[1r](0,100)
     [1t](0,100) = LT2[1b](0,100)   ...etc.
for arrangement like:
____________    ____________
|                 |   |                 |
|   LT2[1]    |   |   PC1[3]    |
|                 |   |                 |
-------------   -------------
____________    ____________
|                 |   |                 |
|   PC1[1]   |    |   PC1[2]   |
|                 |   |                 |
-------------   -------------

**Comment by Flos** [comment]
I have also such a multiscreen setup.
2x Laptops + 2 Additional screens.
The screens are on top of the Laptops. But I can only go from the upper screens from Laptop1<-> Laptop2. On the lower laptop screens the edges are solid, I cant move the mouse to the other Laptop. 
It would be nice to see in the UI the monitor arrangement of the server and clients to mix and match them as you like.

**Comment by sasjafor** [comment]
I support this feature request

**Comment by nb3m** [comment]
Hello, what about this feature? Is it available or it's dead for a long time?

**Comment by molecular** [comment]
I would be willing to pay a reasonable amount of cryptocurrency for this feature to get implemented.

**Comment by nb3m** [comment]
I might me interested. Can you contact me priv?

**Comment by molecular** [comment]
> Can you contact me priv?

ok. but how?
