### ISSUE TITLE
Mac media keys cannot be remapped in config file

### ISSUE THREAD

**Issue by CharlieC3** [symless/synergy-core#6101]
### Operating Systems ###

Server: macOS Sierra 10.12.5
Client: macOS Sierra 10.12.5

### Synergy Version ###

1.9.0-rc3-f987381a0 on both server and client

### Expectation ###

When I start playing music on the server and then switch focus to the client, pressing the Mac media keys should play/pause/change volume on the server computer.

### What I'm seeing ###

When I start playing music on the server and then switch focus to the client, pressing the Mac media keys do not affect the server. Instead, the keys only affect the computer which currently has focus.

### Steps to reproduce bug ###

1. Connect Server and Client computers using default settings for Synergy.
2. Start music playing on Server. Verify media keys work while on server.
3. Switch over to client computer using Synergy. The media keys, they do nothing (to the server)!

### Other info ###

* When did the problem start to occur? When I updated from synergy 1.7.6 to 1.9.0-rc3.
* Is there a way to work around it? Yes, only use media keys when focus is on the server. But the fact this once was working and now isn't isa bit frustrating.
* Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment]
This is by design. Synergy considers the screen your cursor is on is the one you focus on. So when you press media keys when your cursor on a client, all those keys will be redirected to this client.

Maybe what you are after is a way to allow you still pass key to server even when your cursor is on a client, is this right?

**Comment by CharlieC3** [comment]
@XinyuHou Ah ok, yes that is correct.
I've tried creating a Synergy config file on the server and using that to define the mapping of keys, but it doesn't seem to change anything regarding the media keys. Any help on it is appreciated:
```
section: screens
  0136m318224lm.corp.espn.pvt:
    halfDuplexCapsLock = false
    halfDuplexNumLock = false
    halfDuplexScrollLock = false
    xtestIsXineramaUnaware = false
    switchCorners = none
    switchCornerSize = 0
  0136m312621dm.corp.espn.pvt:
    halfDuplexCapsLock = false
    halfDuplexNumLock = false
    halfDuplexScrollLock = false
    xtestIsXineramaUnaware = false
    switchCorners = none
    switchCornerSize = 0
end

section: links
  0136m318224lm.corp.espn.pvt:
    left = 0136m312621dm.corp.espn.pvt
    right = 0136m312621dm.corp.espn.pvt
  0136m312621dm.corp.espn.pvt:
    left = 0136m318224lm.corp.espn.pvt
    right = 0136m318224lm.corp.espn.pvt
end

section: options
  relativeMouseMoves = true
  screenSaverSync = true
  win32KeepForeground = false
  clipboardSharing = true
  switchCorners = none
  switchCornerSize = 0
  keystroke(AudioPlay) = keystroke(AudioPlay,*)
  keystroke(AudioDown) = keystroke(AudioDown,*)
  keystroke(AudioNext) = keystroke(AudioNext,*)
  keystroke(AudioPrev) = keystroke(AudioPrev,*)
  keystroke(AudioStop) = keystroke(AudioStop,*)
  keystroke(AudioUp) = keystroke(AudioUp,*)
end
```

Otherwise, can you direct me to a download of an older version of Synergy (like 1.7.6)? I can't seem to find a page to do that on the Synergy website, and I'm unable to rebuild it from source code due to build errors.

**Comment by nlyan** [comment]
All key remapping is disabled on OS X while you're off the primary screen. This is because they're actually implemented by registering them OS X's native "hot key" API, which stops us from being able to receive and transmit raw keystrokes to clients.

The problem here is we haven't implemented hot key lookup inside the onMediaKey handler like we do for the onKey handler.

Relevant section of the code here:

https://github.com/symless/synergy/blob/c30301e23424db1125664da17deb8c3aa6aec52d/src/lib/platform/OSXScreen.mm#L1282
