### ISSUE TITLE
Setting to limit reconnect retry attempts

### ISSUE THREAD

**Issue by ghost** [symless/synergy-core#6120]
I've got a laptop that I'd like to use with synergy, as many of us do, but I don't want to leave the Synergy client running, constantly trying to connect, while I'm out on the go, nowhere near my home setup. I'd like for Synergy to be able to either detect charging, a specific Ethernet connection, or a specific IP address.

**Comment by XinyuHou** [comment]
@Finalbrez 
Could you give us some details about why you don't want the reconnecting feature?

**Comment by Finalbrez** [comment]
I don't want my laptop constantly looking for my server IP address because my laptop is often not on my home network. It would be wasting my battery life and hindering performance (even if by a negligible amount). I know the specific conditions that my laptop will be under when I want to activate synergy. It will be connected to Ethernet not Wi-Fi, it will have a new unique IP address, it will be charging, and maybe eventually it will have a new monitor plugged in. I am looking for a way to detect those conditions and start the client when those conditions are met. I have tried synergyc from Task Scheduler, but it will not reliably activate, gets force killed when taken off battery, has a massive command prompt window pop up, and cannot properly detect my network so it always runs when plugged in. I was simply hoping for a way to do this directly through the software that detects the conditions I listed above, tries 10 times and shuts off if it could not connect. Simply to save battery life while not at home or in specific conditions at home.

**Comment by glpatcern** [comment]
Hi there,

Some input for something very much related. In my case, Windows 10 client laptop + Fedora 27 server desktop (at work), Synergy Pro 1.10, I rather see the opposite: after the laptop runs sufficiently longer outside the corporate network (e.g. at home, or anywhere else), the client does stop attempting to reconnect and just sits there. See the first lines of the log:

![synergy_client_windows_capture](https://user-images.githubusercontent.com/6871173/44137367-7d183dd2-a070-11e8-9d2f-424c02570c79.png)

But then, once reconnected to the corporate network, it never reattempts to reconnect, and requires the user to open the GUI and click 'Start'. This is what I did in the screenshot above at 9.36.

Therefore, the enanchement would be - on top of "stop trying to reconnect after a given number of retries" - also detect any change of IP address (I do not think anything else really matters) and reinitiate the reconnecting loop.

And thanks for your revived support of Synergy 1!
