### ISSUE TITLE
Service hangs after GUI is opened

### ISSUE THREAD

**Issue by bdmihai** [symless/synergy-core#6251]
### Operating Systems ###

Server: Windows 7
Client: Windows 7

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

Synergy 1.8.8 compiled with MSVC2015 x64. Start the service synergyd. After you start the GUI the synergyd hangs 100% thread load. 

Solution: After replacing QS_ALLEVENTS with QS_ALLPOSTMESSAGE in file MSWindowsEventQueueBuffer.cpp everything worked as expected.

It was a very strange behavior... and difficult to find. I do not understand why this happens.

### Other info ###

On windows 10 it did work in both variants. 
The brahma-dev/synergy-stable-builds build worked fine on windows 7.

**Comment by yupi2** [comment]
It's because of it not being compiled targeting Windows XP. If it's not targeting Windows XP then it includes Windows 8 and Windows 10 event definitions in the headers which do not exist on Windows versions below and thus gets stuck in a loop that just errors instead of waits on events. Defining `WINVER=0x0501` and `_WIN32_WINNT=0x0501` makes it only use Windows XP definitions. My fork https://github.com/yupi2/synergy has this done because I experienced the same bug.

**Comment by nlyan** [comment]
This bug actually blocked the release of v1.9.0, which was built under our v2.0 build environment, hence the changes to the target OS.

@bdmihai I assume you mean QS_ALLINPUT, not QS_ALLEVENTS

**Comment by bdmihai** [comment]
Yes... it was about QS_ALLINPUT. 

The fact is that these defines are actually a combination of flags that depend on the windows version. This could explain why certain combinations work on a windows 10 and not on windows 7 (the flag is actually not present in the old OS implementation). If defining WINVER windows 10 works due to backwards compatibility.

In your opinion, is there a reason not to use a single flag (eg. QS_ALLPOSTMESSAGE )

**Comment by nlyan** [comment]
Using a mask that's too broad should be harmless.

**Comment by mrsixw** [comment]
Hi, is this still a bug with the 1.9 release?

**Comment by nlyan** [comment]
This fix went in to v1.9 and can probably be closed
