### ISSUE TITLE
Synergy 2.0 & later is now closed source... please update your repo's description to reflect that

### ISSUE THREAD

**Issue by arooni** [symless/synergy-core#6265]
Congrats on your 2.0.6 release (https://symless.com/forums/topic/5348-synergy-206-is-ready/)

When will you update this repository with this tagged release?  Kind of hard to build from source if there's no source to build from :) 

PS: Thanks for a great product, really looking forward to upgrading from 1.8.6

**Comment by arooni** [comment]
Looks like you've closed source after the v2 release.  Perhaps you could update this repo's description to save people time searching for the latest release.

https://www.reddit.com/r/linuxmasterrace/comments/72gp5t/synergy_20_goes_closed_source/

**Comment by nlyan** [comment]
The Synergy core process shipped as part of v2.0 is in master. We use a submodule so it's always up to date, it's just most of the development effort since v1.9 has been outside of core, so we're not making a lot of commits here.

The README has been updated to reflect that this repo is for the "open source core component".

Closing
