### ISSUE TITLE
Serial Key Required when software is open source.

### ISSUE THREAD

**Issue by duaneking** [symless/synergy-core#6283]
### Operating Systems ###

All OS's supported.

### Synergy Version ###

1.8+ Tested

### Steps to reproduce bug ###

Install app from open source. Get a "what is your registration key" popup.

### Other info ###

As the software is open source we can easily reverse engineer this but the fact is since its GPL we shouldn't have to.

**Comment by nlyan** [comment]
The software being open source doesn't preclude commercial licensing. Unlike e.g. Google Chrome (which is proprietary and not entirely open) we just open source everything, including the serial key / license management code.

WONTFIX

**Comment by solbu** [comment]
@nlyan: You have completely missunderstod the FSF article on selling software. It does not in any way talk about licensing keys. It is explisitly discussing selling physical copies of the software, not serial keys.

Stallman have said numerous times in the Q&A section of his talks that Free Software which requires serial keys in order to operate, should be treated as if it was proprietary, and everyone should avoid it.


This issue just came up via a Mageia user reporting a bug via one of our mailing lists, and this bug repport was the most relevant search result.
