### ISSUE TITLE
TIS/TSM in non-main thread environment

### ISSUE THREAD

**Issue by nbolton** [symless/synergy-core#6326]
### Operating Systems ###

Server: macOS 10.13
Client: macOS 10.13

### Synergy Version ###

2.0.12, 1.10.0

### Steps to reproduce bug ###

1. Run on macOS (client or server)
1. See warning in log: `TIS/TSM in non-main thread environment`
1. See no negative side effect

https://synergy-logs.symless.com/794c9ad95a14dd594ce25f5eb7029c40/logs/18-2018-06-28T07-50-30.log

### Other info ###

The warning seems to cause no ill effects, other than making users panic.

**Comment by rwuwon** [comment]
I must admit this initially caught me off-guard while troubleshooting, when my whole terminal (except one line) was flooded with the error/warning.

Normally during operation, the message doesn't bother me as I can clearly see whether my connection is working or not.

However, when starting the server in -f(oreground) mode, it's easy to miss the bottom line - e.g., `synergy-core[29959:794828] starting cocoa loop` - which indicates everything is in fact normal.

Would it be a good idea to make that small `starting cocoa loop` message more prominent or descriptive? In lieu of an elegant way to suppress the warning, perhaps something like extra lines of ASCII art padding around the "starting cocoa loop" line could be useful, because right now I don't see any clear descriptive feedback for a successful server start.

I'm otherwise successfully using v2.0.0-stable compiled from source on the macOS end and am very happy with how it works between Fedora 28 and macOS 10.13.5 (including through an SSH tunnel, once I located the instructions in the [Core User FAQ](https://github.com/symless/synergy-core/wiki/Core-User-FAQ#what-securityencryption-does-synergy-provide) and wrapped my head around it).

**Comment by 1p0t** [comment]
Can confirm that my terminal is flooded with this "error" too when I start the server in foreground mode, but the cocoa loop starts anyways and my setup works smoothly (Server: Mac OS 10.13, Client: Ubuntu 16.04, Synergy v2.0.0). I would support @rwuwon's suggestion to make a message for a successful server start more prominent.

**Comment by Jingxuan-Wang** [comment]
My comma and period are not working on client side as this warning pops out whenever I click on the key
