### ISSUE TITLE
Windows client does not always wake from sleep

### ISSUE THREAD

**Issue by marquedej** [symless/synergy-core#6362]
### Operating Systems ###

Server: macOS Sierra (10.12.6)
Client: Windows 10 (1803, OS Build 17134.165)

### Synergy Version ###

2.0.12-beta on both server and client hosts

### Command Line ###

Synergy is started via:

  `/Library/LaunchAgents/com.symless.synergy.synergy-service.plist`

which, in turn, calls:

  `/Applications/Synergy.app/Contents/MacOS/synergy-config --service`

### Steps to reproduce bug ###

1. Put Win 10 host to sleep: Click on Win Logo > Power > Sleep
 As expected, Win 10 host is "asleep" :slightly_smiling_face:
 As expected, Synergy service on Win 10 is "sleeping" as well, so it cannot be accessed
2. Wake Win 10 by pressing power button/keyboard/trackpad
3. **Expected result**: Synergy "wakes up" and I can once again access it from my Mac's keyboard/mouse
4. **Actual result**: I need to restart the Synergy service on Win 10 before I can access it from my Mac's keyboard/mouse

[Note] It seems somewhat intermittent. _Sometimes_ the Win 10 host will be accessible from Mac's keyboard/mouse via Synergy. However, more often than not, it is not.

### Other info ###

* This has been occurring since I began using Synergy 2
* Workaround is to manually restart the Synergy service on the Win 10 host
* Does this bug prevent you from using Synergy entirely? No. It's just a nuisance every morning when I start my day. :-)

**Comment by nbolton** [comment]
Thanks for raising a bug report! If there's anything I can do to help, please let me know.

**Comment by marquedej** [comment]
Hi Nick,

Yeah, sure.

I'll do some more tests and add any further details, should I come across any. :-)

Thanks,

	-- Mark

**Comment by dofisher** [comment]
I am having the same issue as of latest release 1.10.3-stable-ca35737a.  
Windows 10 Enterprise 1709 client 
Mac OS 10.13.6

**Comment by Raniz85** [comment]
I'm having the same issue but with a Windows 10 as the server

Server: Windows 10 Pro 1903 running Synergy 1.10.3-stable-ca35737a
Client: Arc Linux with kernel 5.3.7 running Synergy 1.10.3-stable-0badc0de

**Comment by prokher** [comment]
Having the same issue on tha latest Synergy, downloaded today (

**Comment by mstormo** [comment]
The issue still persists today, @nbolton.

If you look at the Windows Event log when starting up from sleep, an indication might be that the Bonjour Service is also erroring a lot, which might be why Synergy is crashing at the end, not handling Bonjour errors gracefully?

The Synergy service, in the end, crashes with a 0xc000005 exception (Access Violation)
![image](https://user-images.githubusercontent.com/1500/99802415-47862c00-2afd-11eb-948e-d8562dcfc1b7.png)

The Bonjour error is a bunch of "Unexpected conflict discarding ...", "Local Hostname X.local already in use; will try X-2.local instead", "ProbeCount 0; will deregister  Y X.local. Addr [IP]" and "Resetting to Probing"; a total of 24 error messages.
The Bonjour service does not crash, however, and is running fine. My guess it's just a wake-up issue, where Bonjour needs some time to resolve conflicts from when it was put to sleep.

No matter what though (especially since I'm not even using Bonjour in my setup), Synergy should not be crashing on wake from sleep, and a 0xc000005 exception indicates accessing of a bad pointer, and should be relatively easy to fix.

**Comment by andreacndn** [comment]
Hi @marquedej can you reproduce the same issue using Synergy 1.12.2?
