### ISSUE TITLE
Ubuntu 14 install fails with libqt5core5a dependency

### ISSUE THREAD

**Issue by sangwoo-joh** [symless/synergy-core#6365]
### Operating Systems ###

Server: Ubuntu 16.04.5 LTS

### Synergy Version ###

v1.10.0 stable_b36+275cdc1c_debian_amd64

### Command Line ###

`sudo dpkg -i synergy_1.10.0 stable_b36+275cdc1c_debian_amd64.deb`

### Steps to reproduce bug ###

 - just run the command line on Ubuntu 16.04

This version of synergy depends on `libqt5core5a` with >=5.7.0 and `libssl1.1` with >=1.1.0, but Ubuntu 16.04 has only version 5.5.1 and 1.0, respectively.
Is this due to a version issue of Ubuntu itself, or some dependency issue of synergy?
Thanks for your help.

**Comment by AvishayRapp** [comment]
Hey, I had the same issue on another machine, you need to manually update the package.

This will update your package to the right version:

```
sudo apt-get update
sudo apt-get install libqt5core5a
```

Because I don't know if your system is 32bit or 64bit, here is the download link to both:
`https://pkgs.org/download/libssl1.1`

Update both packages and run the install command again ( Copy & Paste ):
`sudo dpkg -i synergy_1.10.0 stable_b36+275cdc1c_debian_amd64.deb`

Please let me know if this worked for you like it did for me.
I hope I helped!

**Comment by skicombinator** [comment]
@AvishayRapp Thanks for your help.
My system is 64bit, and I tried both command but my package list only has libqt5core5a 5.5.1 version.
I fixed problem just by installing the older version (1.8.8) from your [legacy page](https://symless.com/help/s1-troubleshooting/s1-legacy-os)

**Comment by LeadManPL** [comment]
@sangwoo-joh : Current LTS for Ubuntu is 18.04 . Could you upgrade your OS ? I have no issues with dependencies wit Ubuntu 18.04 , so this would solve your issue, and Synergy Team could use their time on fixing bugs that are still present for many years. If that works for you, please close this issue.

**Comment by sangwoo-joh** [comment]
@LeadManPL , Thanks for your comment and my apology for the late update.
Recently, I moved to Ubuntu 18.04 LTS and had no trouble with installing & using the latest synergy application.
Thank you so much, and thanks for this great software.
I close my issue.
