### ISSUE TITLE
Support for logging in using different users on Linux

### ISSUE THREAD

**Issue by rugk** [symless/synergy-core#6416]
### Operating Systems ###

`/etc/issue`just gives this 
```
\S
Kernel \r on an \m (\l)`
```

I doubt this is useful. :smile: 

Here better: Fedora 28, x64, GNOME

### Synergy Version ###

synergy-core 2.0.12, protocol version 1.6

### Steps to Reproduce ###

On one device (tested with server):

1. Run synergy.
It connects.
2. Switch user.
3. Log in as other user.
4. Connect.

What happens: The client device cannot connect back to the server, it seems to try to get a connection to the old server.

What should happen: The best would be if the app would detect it, and switch to `user@computername` in the display and, of course, successfully connect.
So one can switch users on one device and continue using Synergy.

### Run Method ###

Config app

**Comment by dragon788** [comment]
This already works, it just requires you to adjust your system configuration in order to manage starting and stopping the server as each user as well as using a custom configuration in a path accessible to all users.

The reason for this extra setup is that users are isolated from one another by many mechanisms, and programming a service to handle this dynamic user switching on the server side would be very challenging. The challenge is Synergy requires a GUI session and these have mechanisms ensuring only your user's processes can interact with things like the clipboard and input devices (so somebody can't write a service that just monitors the clipboard and pulls out passwords or latches onto the keyboard to record everything that is typed).

Due to how Synergy is currently written the config files and SSL certs (if using that option) live under the `${HOME}/.synergy` or `${HOME}/.config/Synergy` directories which are in the current user's HOME folder, so to make multi-user Synergy work (server or client) you basically need to move that config to the system-wide `/etc/xdg/Synergy` (on Linux) or `%PROGRAMDATA%` (on Windows) so that it is accessible by any user and then launch Synergy with a path to the custom configuration if it doesn't automatically detect it. There are some "sane" fallbacks in place in Synergy so it can be tough to know whether it is using a custom config when you don't supply one unless you do debug level logging.

I don't have time to walk through the whole process, but if you take a look at the solutions for starting automatically on the wiki. https://github.com/symless/synergy-core/wiki/Startup You can see where it suggests adding a script to start with your GUI that runs Synergy and then kills and re-runs inside your user session using another script.

If you need more help you can ping me here and I'll try to expand on the required setup.
