### ISSUE TITLE
Portuguese special chars cause intermittent accents

### ISSUE THREAD

**Issue by danielalarconf** [symless/synergy-core#6429]
### Operating Systems ###
Server: Windows 10
Client: Windows 10

### Synergy Version ###

- Synergy 1: 1.10.1

### Steps to Reproduce ###

1. Setup Portuguese keyboard
2. Type  "não" on Server
3. Intermittently, "nãõ"  appear on the client.

**Comment by coredump** [comment]
@nbolton I did some testing on this, and seems to be something related to the speed one types. the nãõ thing will happen (just like it just did) but if you delay ever so slightly the o, or any letter that comes after the one with the tilde, it will work as expected. It doesn't matter what letter or accent you use, if you type it too fast you get it. Some examples:

```
ãñ éá éó âô
```
I think it's more visible on the ãõ combination because that's a very fast combination when typing portuguese on QUERTY keyboards. the other combinations é á ó are less common and for that reason typed slower.

**Comment by DiThi** [comment]
I'm using Synergy once again, and once again I have this problem. Dead keys don't work properly when writing fast. 

Alternating tilde and a in the client: á´a´a´áá´a´a´ááa
In the server: áaaaaaaaáa (even without connected clients)
Without synergy: ááááááááá

I did make the bug #5007 but was closed as stale. It was and it still is a dealbreaker and I'm surprised the problem is not reported more frequently.

**Comment by AlanFPS** [comment]
Can this be`reopened? It won't stop adding random commas and tildes to words when using spanish keyboàrd.

**Comment by sithlord48** [comment]
this is just #6599
