### ISSUE TITLE
Version check no longer works

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6535]
### Operating Systems ###

All

### Synergy Version ###

v1.10.2 and earlier

### Steps to Reproduce ###

1. Start synergy <=1.10.1
1. See that there is no banner informing the user there is a newer version 

### Extra Info ###

The config app checks the version number for the whole app.

The Website changed its structure from just symless.com to symless.com and members.symless.com

The application requests the current version number from https://symless.com/version which has moved to https://members.symless.com/version

Due to the way the version is grabbed from the page redirects will not work, the page must be a text document that returns the version number and nothing else.

**Comment by Jnewbon** [comment]
It is suggested to move the version URL to something that can be changed with ease, for example, synergy.symless.com/version that is separate from the website structure and can be controlled independently from updates to the website itself.

**Comment by Jnewbon** [comment]
Having thought about this more it may be better for the URL to be `version.symless.com/synergy`

This would allow one CNAME to serve all the version information for any product. `version.symless.com`

And keep the customizability of multiple products in the future `/synergy`, `/synergy2`, `/NextMajorVersion` etc and changes to one will not affect any other product

**Comment by nifr** [comment]
+1 for the dedicated `version.symless.com` sub-domain.

Is there - as of now - a similar API for Synergy2 available? 

I'd be interested in a (reliable) API to fetch the latest version in order to be able to create the download URI for the .deb package during automated provisioning with salt/ansible.

I'm currently using the [releases](https://github.com/symless/synergy-core/releases) page for Synergy1. As there's no public repository for synergy2 this is not an option.
