### ISSUE TITLE
Synergy spawns hundreds of zombie processes

### ISSUE THREAD

**Issue by Jnewbon** [symless/synergy-core#6567]
### Operating Systems ###

Windows 10

### Synergy Version ###

<= 1.10.3

### Steps to Reproduce ###

1. Let synergy run for a couple hours
1. Run up RamMap tool
1. See hundreds of syntool.exe and synergy(c|s) processes

### Extra Info ###

![image](https://user-images.githubusercontent.com/48688400/66388868-ef569e00-e9be-11e9-82ae-7e75c4fe683b.png)

**Comment by sliftist** [comment]
I think I have you beat, synergy spawned 339424 zombie processes on my machine:
```C:\Users\quent\Dropbox\repos_external\blogstuff\FindZombieHandles\prebuilt>FindZombieHandles.exe
341592 total zombie processes.
    339424 zombies held by synergyd.exe(4076)
        169712 zombies of syntool.exe
        169712 zombies of synergys.exe
    1410 zombies held by svchost.exe(6876)
        1058 zombies of Code.exe
        277 zombies of cmd.exe
        25 zombies of chrome.exe
        16 zombies of node.exe
.
.
.
```
(output from FindZombieHandles, at https://github.com/randomascii/blogstuff/tree/master/FindZombieHandles/prebuilt ).

The zombie processes don't just cause memory usage, if you have enough of them they mess up memory management, causing ntoskrnl.exe!MiWalkPageTablesRecursively to run forever (causing 100% cpu usage on a single core, and slowing down other IO operations).

Sorry if I can't be more help debugging it, I love Synergy and I used it a lot when I was developing on my Raspberry Pi, but I had to uninstall Synergy because I haven't used it for years and the spawning of zombie processes was really slowing down my system.

If it helps it the version that was installed when I uninstalled it was 1.8.8, which looks old, so the issue might be fixed now. Will report back if I use Synergy again (after I update to the latest version) and see this issue again.

**Comment by kfts** [comment]
I've been dealing with memory issues for months now and just figured out this was the cause. My memory usage in task manager would slowly go up over time even with all my programs closed.

Noticed I had a 7+GB page file in Rammap and found thousands of the zombie processes from Synergy. Uninstalled it and problem is finally solved!

**Comment by Jnewbon** [comment]
As a note for this issue, would appear you can clear out all the zombie handles by stopping and starting the synergy service in task manager services tab which doesn't require a reboot of the machine.

I have identified the cause and resolved the issue in testing, but these fixes will be included in the next release (1.12.1 probably)

**Comment by Jnewbon** [comment]
I have a test build out for this that you can try here

https://snapshots.symless.com/public/1.12.0-dev6567/

Please let me know if this doesn't solve the issue at hand

**Comment by MortenHannemose** [comment]
I'm on version 1.12.2-stable-a52ccb2d
After my computer has been on for 1 day and 20 hours, Synergy has created a number of zombies (which increases over time)
```
83 zombies held by synergyd.exe(5092)
        42 zombies of syntool.exe
        41 zombies of synergys.exe
```

@Jnewbon Should I open a new issue?

**Comment by andreacndn** [comment]
Hi @MortenHannemose, we have fixed this bug in 1.13.0, soon to be released.

**Comment by MortenHannemose** [comment]
I'm on version 1.13.0-stable-bdb8f767, and `synergyd.exe` is still generating zombies of `synergys.exe`

```
    178 zombies held by synergyd.exe(21808)
        178 zombies of synergys.exe
```

**Comment by andreacndn** [comment]
SYNERGY-803

**Comment by MortenHannemose** [comment]
Any update on this?
Synergy is still generating a few zombies in 1.13.1-stable-063519a8.
```
    117 zombies held by synergyd.exe(3544)
        117 zombies of synergys.exe
```

**Comment by andreacndn** [comment]
@MortenHannemose Thanks for the update, we'll investigate the issue again

**Comment by MortenHannemose** [comment]
Update that this is still occurring under 1.14.0-stable.67d824b8:
```
    202 zombies held by synergyd.exe(5408)
        202 zombies of synergys.exe
```

**Comment by MortenHannemose** [comment]
This is still occurring under 1.14.6-snapshot-88fdd263
```
 63 zombies held by synergyd.exe(6596)
        63 zombies of synergys.exe - process handle count: 63 - thread handle count: 63
```
