### ISSUE TITLE
macOS Catalina Dark UI support

### ISSUE THREAD

**Issue by wreiske** [symless/synergy-core#6583]
### Operating Systems ###
Server: Windows 10
Client: MacOS 10.15 (19A603)

### Synergy Version ###

Latest master build, master branch, git head 52c3337acd860916ef8d5383c1bf64e4889933d1

### Steps to Reproduce ###

1. Checkout latest master build on macOS Catalina
2. Follow the steps at https://github.com/symless/synergy-core/wiki/Compiling
3. Build and run

**Behavior**
Connecting works fine, everything seems to work (except I can't get the bundle to do anything... maybe another issue there?).

However, the UI is almost unreadable when dark mode is enabled.
![image](https://user-images.githubusercontent.com/6295044/67709694-d7a68000-f994-11e9-85fa-1c6a3204d505.png)

**Expected Behavior**
Support the dark UI on macOS.

**Other information**
We might need to build with Qt 5.12.1 or later in order to support the dark UI. I built this with 5.9.8. Is the documentation still up-to-date regarding the Qt version?

**Comment by Jnewbon** [comment]
This will probably be fixed with the next release of synergy, due to requirements with Catalina I have updated the build machine and with that the QT version. 

I'm still in this process however but currently, this is what it looks like and this will be part of v1.11.0 which in entering QA now. 

![image](https://user-images.githubusercontent.com/48688400/67784787-3129b000-fa64-11e9-9ec5-e9c951dca377.png)

We are looking for people willing to help test new releases, as there are many different setups and configurations people use that we can't replicate in a timely manner. Would you want to test out the releases when they become available?

**Comment by Jnewbon** [comment]
@wreiske Update for you turns out its not the QT version that's the problem. QT seems to save some preferences to do with the broken theme on the machine. so even though your build's dark theme may work fine a previous builds theme is still there somewhere. 

I managed to fix this by following the [reinstall from fresh](https://symless.com/help/articles/s1-reinstall) instructions, the only problem with this is it resets the synergy configuration as well. I'm sure there is a probably way to only erase the theme settings though.
