### ISSUE TITLE
Impossible to build with current instructions; please add screenshots for options in QT Studio

### ISSUE THREAD

**Issue by arooni** [symless/synergy-core#6607]
For those of us who still choose to exercise the GNU license to build your wonderful software ourselves, your wiki instructions are woefully inadequate.  I wasted 30 minutes of my life trying to follow along via software I've never used before.  Please do your users a favor and post screenshots of the options as simply "find this option, then do this" in very complicated software I've never used before isn't fair.  

For instance the instruction:
"Edit the Qt kit "Environment" field under Tools -> Options -> Build & Run -> Kits and add BOOST_ROOT=/home/<user>/boost"

Guess what, there's no Kits option under build and run options.  Plus even if you do manage to create a new kit; it's not clear how to fill in the values.  Also there's no current directory at /home/arooni/boost ;;; so how does that work?

The instruction "Open CMakeLists.txt"  -- on latest stable release there is no CMakeLists.txt ; but rather CMakeLIsts.txt.user

The instruction "Untick "Imported Kit" -- where is this option in the UI?  I couldn't find it

The instruction "Untick all except Debug and Release"  -- where am I clicking this?  

I understand the business sense to create complicated instructions to prevent people from building it themselves but I think this goes against the spirit of the GNU public license and what you want to stand for as a company.

Right now you could replace your wiki with a simple "don't try building this -- it'll be too difficult with these current instructions" and you could save a lot of people time.

Thanks very much.

**Comment by badgenes** [comment]
I also have this issue.  As I was following the steps and came to the QT portion I too had the same questions.  Prior to that during the installation of QT if the user select "Desktop Qt 5.12.5" 44GB of installation takes place! At this point I first suspected what the OP surmises is the real issue: intentional obfuscation to thwart users from compiling on their own.  This flies in the face of Open Source!  You should be ashamed at what you've done.  Be closed source and be honest for God's sake or post instructions that are relevant, take the shortest path and are concise.  I've seen projects by teens display far better documentation than what you have here.

My intent in compiling was to DEMO your product for my BUSINESS and consider a RESALE partnership as well as PURCHASE for my staff.  You've lost a customer and a potential reseller, WTG.

**Comment by AnrDaemon** [comment]
The VS 2019 build instructions are unusable.

**Comment by leonovvalentin** [comment]
Have the same issue with instruction for Mac OS.

**Comment by JakeBenjamin** [comment]
Same Issue on MacOS

**Comment by AnrDaemon** [comment]
A year later, still unusable.

**Comment by haqk** [comment]
This build process seems to work fine: https://github.com/debauchee/barrier-wiki/blob/master/Building-on-Linux.md

**Comment by AnrDaemon** [comment]
After much trial and error, I've managed to set Qt in a way that satisfied VS 2019. My builds are running okay so far.
