### ISSUE TITLE
Ubuntu 19.04 Can't leave screen unless application is open and touching that side of the screen.

### ISSUE THREAD

**Issue by ceiphr** [symless/synergy-core#6651]
### Operating Systems ###

Server: Ubuntu 19.10/19.04 (Wayland)
Client: MacOS Catalina

### Synergy Version ###

Synergy 1: synergys 1.11.1-stable, protocol version 1.6

### Steps to Reproduce ###

1. Run Synergy on both computers
2. Have no windows open on server
3. Attempt to leave window to go to client
4. Can't exit screen, logs show nothing wrong

Expected: Leave server, enter client
Actual: Never leave server, no issues raised in server or client

### Log URLs ###

Server: https://paste.ee/p/5qhoZ
Client: https://paste.ee/p/Czc98

### Extra Info ###

Having Firefox or Thunderbird full screen or next to the side of the monitor where I leave the screen allows for expected behavior. Having no windows open or GTK applications open gives the actual behavior.

I have the following hotkey enabled on the server: CTRL + TAB → lockCursorToScreen(toggle). Deleting it and restarting the server doesn't help.

Testing on Wayland and X.Org results in the same issue.

I don't believe this is an issue related to the distribution version since 19.10 isn't a significant step-up from 19.04.

**Comment by Jnewbon** [comment]
Synergy currently doesn't support Wayland 

Closing due to existing issue #4090

**Comment by ceiphr** [comment]
@Jnewbon,
> Testing on Wayland and X.Org results in the same issue.

I currently use Wayland, but could reproduce the issue in X.Org. Please re-open the issue. Thank you.

**Comment by Jnewbon** [comment]
Okay, didn't see that qualifier.

**Comment by wozhub** [comment]
Having exactly the same issue. Let me know if i can be of any help.

Server: Ubuntu 20.04 (Wayland)
Client: Debian 9 (Openbox) and Lubuntu 20.04

**Comment by kinekt4** [comment]
> I currently use Wayland, but could reproduce the issue in X.Org. Please re-open the issue. Thank you.

I'm on Fedora 33 and switching over to Gnome (xorg) has solved my issue.

I did however, tried a couple of other Desktop Enviroments (Xfce/LXQT) before going back to Gnome (xorg) though.

Related (dupes):
* https://github.com/symless/synergy-core/issues/6404
* https://github.com/symless/synergy-core/issues/6191

**Comment by andrewheadricke** [comment]
Experiencing same bug. Ubuntu host (wayland, dual screen), OSX client (single screen), if a browser is fullscreen and in focus it works fine, but if its not full screen OR its not a browser then it wont escape to the other screen. If I switch to X.org the problem goes away, however there are many more significant issues trying to use X.org.

It appears to me that `synergys` is obtaining the active window handle instead of the root wayland handle or wayland desktop handle. Because when moving the mouse around in circles between screens the synergy boundaries tend to match the active window rather than the desktop.
