### ISSUE TITLE
Connection issues due to weak SSL keys on recent OS

### ISSUE THREAD

**Issue by xmstspider** [symless/synergy-core#6667]
### Operating Systems ###
Ubuntu 20.04 LTS (5.4.0-26-generic #30-Ubuntu)

### Synergy Version ###
1.11.1.stable~b58+55ec3105

### Steps to Reproduce ###

I can confirm the same issue as in #6561 is present in recent Ubuntu 20.04 LTS.

``
ERROR: secure socket error: could not use tls certificate
ERROR: openssl error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
``

**Comment by Jnewbon** [comment]
Can you try deleting the certificate and allowing synergy to recreate it
`rm ~/.synergy/SSL/Synergy.pem`

This problem was fixed the issue you linked, but it was decided that if a certificate already exists it would default to that rather then recreate one. 

If the problem persists comment back and I will reopen the issue

**Comment by xmstspider** [comment]
Ok, so the proper fix is:
On Linux, shutdown the Synergy client or server and run ``rm -rfv ~/.synergy/SSL/``
On Windows, shutdown the Synergy client or server and delete ``%USERPROFILE%\AppData\Local\Synergy\SSL``

Start both client(s) and server.

It looks like the fingerprints spooked as well. Now it's working

**Comment by moneyatbo** [comment]
I can also confirm this worked for me.

**Comment by nbolton** [comment]
Duplicate of #6671
Will be fixed by #6669
