### ISSUE TITLE
Systray Icon does not work on initial boot Ubuntu 20.10

### ISSUE THREAD

**Issue by anthonysomerset** [symless/synergy-core#6822]
### Operating Systems ###
Server: Ubuntu 20.10 Desktop
Client: Windows 10 20H2
### Synergy Version ###

synergys 1.11.1-stable, protocol version 1.6

### Steps to Reproduce ###

1. Boot OS (Synergy Auto Start enabled)
2. Synergy notes systray icon not loaded do not close window
3. no systray icon showing

Expected: Systray Icon should be present and no issues with app
Actual: Systray does not show - server seems to run OK but can't reconfigure server side

to workaround i have to identify the synergy processes and kill them via terminal then i can manually re-load the app and it works 100% fine

### Log URLs ###

Unfortunately when i reload synergy app the logs disappear - would appreciate guidance on how to save previous logs

### Extra Info ###

in 20.04 i had no issues - only doing this since upgrade - i have similar behaviour with nextcloud app also (https://github.com/nextcloud/desktop/issues/2597)

fully killing the processes and re-open works OK

**Comment by jayblingham** [comment]
**Operating Systems**
Client: Pop!_OS 20.10, latest updates applied (Uses Ubuntu 20.10 as it's base)
Server: Windows 10 19041.572

**Synergy Version**
1.12-0.stable-cb8064e8 (Thursday, Augusut 27, 2020)

**Steps to Reproduce**
1. Boot OS
2. Login
3. Synergy process starts in the background as a "starup application"
4. Error message appepars: "systray icon not loaded do not close window" (no window appears)
5. Icon missing in system tray
6. Application functions, seemingly without issue (Mouse and keyboard can traverse screens/systems without issue)

**Log URLs**
I was uncertain where to find any logs for the active process (without GUI attached).  When I re-launch the GUI without first killing the existing Synergy process, I get the following in the acitve log window:

[2020-11-03T07:16:53] NOTE: connecting to 'xxx.xxx.xxx.xxx': xxx.xxx.xxx.xxx:24800
[2020-11-03T07:16:53] ERROR: server already has a connected client with name "fake-hostname"
[2020-11-03T07:16:53] WARNING: failed to connect to server: server already has a connected client with our name

I can confirm this on Pop_OS 20.10 which uses Ubuntu 20.10 as it's base.  Both server or client when run at startup give the same "systray icon not loaded do not close window" message.  Synergy seems to run without issue, and keyboard/mouse traverse the screens as normal.  

**Extra Info**

If I manually l start the Synergy gui, it launches as a 2nd instance of the process and produces the error messages as indicated above.

As @anthonysomerset indicated above, if you kill the process and re-launch manually via Gnome menu, it appears as normal in the system tray and functions correctly.

Appreciate any guidance around how to set a debug level, or acquire logs to share (if needed).

**Comment by anthonysomerset** [comment]
From other issues experienced - https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/250 could be the root cause based on other research

for now my workaround is create a basic script that does a sleep 5  && synergy and trigger this as the startup script

**Comment by ignacionr** [comment]
This is great input. Working on it.
@jayblingham would you confirm this is as per configuring on the "Startup Applications Utility" i.e. Ubuntu's?

**Comment by jayblingham** [comment]
@ignacionr Confirmed.

**Comment by andreacndn** [comment]
@anthonysomerset @jayblingham could you please check if the new version solves your problem?
https://symless.com/synergy/releases/synergy-1-13-release-candidate-2

Thansk,
Andrea

**Comment by jayblingham** [comment]
@andreacndn Installed 1.13.0 rc2 and it solves the issue in that the error message is no longer displayed after login and the service connects however; even with "Hide on startup" UNchecked, it still does not display an icon in the task tray.

If I then open the Synergy GUI in order to check/change settings, it does not connect to the running instance, and instead opens a second process indicating that the "server already has a connected client with our name".  The only way I can use the GUI is to kill both the synergy, and synergyc processes, and relaunch the GUI.

Log excerpt:
[2020-12-16T12:42:00] INFO: starting client
[2020-12-16T12:42:00] INFO: config file: /tmp/Synergy.DsfYDT
[2020-12-16T12:42:00] INFO: log level: INFO
[2020-12-16T12:42:00] NOTE: started client
[2020-12-16T12:42:00] NOTE: connecting to 'xxx.xxx.xxx.xxx': xxx.xxx.xxx.xxx:24800
[2020-12-16T12:42:00] ERROR: server already has a connected client with name "<SYSTEM NAME>"
[2020-12-16T12:42:00] WARNING: failed to connect to server: server already has a connected client with our name

**Comment by andreacndn** [comment]
Thank you for the update!
