### ISSUE TITLE
Wayland support, please add a link to the forums

### ISSUE THREAD

**Issue by rubin110** [symless/synergy-core#7127]
> We plan to implement Wayland. Right now, it's mostly GitHub users asking for Wayland. Most of our users are not on GitHub and aren't asking for Wayland yet. Thanks for your patience.

_Originally posted by @nbolton in https://github.com/symless/synergy-core/issues/4090#issuecomment-1000183281_

Hello @nbolton! Could you please add a comment on #4090 to include a link to one of the several posts on the Symless Synergy forum so that the ~70 participants asking for that feature (and also future GitHub plus oners) can also follow up with your request to add in their voice to where most of your users provide their input? I'd do it myself but #4090 is now locked. Here's a link to a good post on your forum...

https://forums.symless.com/topic/4798-wayland-support/

Thank you so much for supporting the Linux community! We all really appreciate it!

PS, CCing the commenters to #4090 so they also know where the right spot is the provide our +1 for this feature:

@aairey @acdingman @aensley @arquio @bcdonadio @brianjmurrell @brunosantosnasajon @btaens @cadesalaberry @CapOM @cbarrerang @cekstam @chrisbliss18 @circuit-breaker @coolhandlance @cuviper @danielheaton @DarrellDuane @daveboutcher @davidkirwan @DeftNerd @Djhg2000 @dolphin85204 @dotted @easytarget @Ernillew @fenrig @fftux @ghost @gilbertw1 @gregsheremeta @Heimo001 @hertzg @hmic @Ironchunk @jamesgreenblue @jsight @Kami-no @kd5ftn @Kirk-H @klm46 @Lerentis @lig @mallardduck @michaelwheatland @mgc @neilmayhew @oxayotl @Pajinek

**Comment by rubin110** [comment]
CCing a few more:

@ph03 @phoenixdigital @pierrre @polarathene @ppaalanen @preactive @Quip11 @raynix @rboati @renatovico @rpjohnst @RusDavies @seaweeduk @sgala @skela @skoslowski @StephanMeijer @tbporter @techgnosis @theburn @thegass @tonylambiris @trejjam @tswfi @viniciushsantana @wiltonlazary @wirecat

Thanks again @nbolton!

![bitmoji](https://sdk.bitmoji.com/render/panel/24d97e36-b0df-41af-b867-820365c4a5e0-15b3dad9-b3fb-4e0d-acb8-9d0694a55833-v1.png?transparent=1&palette=1&width=246)

**Comment by lig** [comment]
Well, at some point there were a lot of users from GitHub. As for me I haven't been using Synergy for a long time.
And I don't think I'm interested in trying it again after so many years of false promises.
Please, don't plan, don't mention, just do and after that you could gain some trust back.
P.S.: I have got a Synergy license via donation a long time ago.

**Comment by nbolton** [comment]
Absolutely agree. No more promises, only action. When we are able to implement Wayland, the first you'll hear about it is when you're testing it, I will let you know.

**Comment by Kirk-H** [comment]
I'm also in the "Too little too late" camp here. You missed your window, most of us found other solutions.

**Comment by nbolton** [comment]
Understood, sorry to hear it didn't work out. What other solution did you go with?

Merry Christmas 🎄

**Comment by preactive** [comment]
@nbolton I ended up just getting hardware that could run three screen an my other hosts I changed how I used them and just do work over ssh/terminal now since it has been so long.

I wanted to say something in regards to a comment of yours on another thread: "Right now, it's mostly GitHub users asking for Wayland. Most of our users are not on GitHub and aren't asking for Wayland yet." That would be true because most users update they systems and they are encouraged to use Wayland. Thus they are bumped from being able to use your product. Thereby, your statement seemed anecdotal at best. At least that was the way I felt when I read it.

I do hope you can figure out a working solution.  I would love to utilize your application on a rpi4 cluster as well as the resources on the rpi4 are smooth enough for regular use.

**Comment by nbolton** [comment]
Fixed by: https://github.com/symless/synergy/pull/7449
