### ISSUE TITLE
Please Answer..Important!

### ISSUE THREAD

**Issue by foco76** [symless/synergy-core#7227]
what is the difference between synergy 1 , synergy 2 and synergy 3?
Thank you!

**Comment by chatilaah** [comment]
From a consumer's perspective, Synergy 1 uses local-network based communication. While Synergy 2 uses internet-wide based communication, but users (including myself) encountered issues with the latter due to being unintuitive and unpractical. Synergy 2 required the connected machines to be connected to the internet at all times, which instantly became unpopular and criticized by users.
From a technical perspective, Synergy 2 was a big step forward because it eliminated the need to maintain trivial tasks (i.e threads) by using third party libraries like "Boost". Synergy 1 was programmed top to bottom almost relying on nothing, except for "OpenSSL".
P.S. I haven't tested Synergy 3 to give you my take on it. I do have plans though.
